// lib/area-config.ts
// Geohash prefixes computed from: node scripts/compute-geohashes.mjs
// Precision 4 ≈ ~20km cell (city-level pages)
// Precision 5 ≈ ~5km cell (area-level pages)

export interface AreaConfig {
  slug: string;
  name: string;
  city: string;
  geohashPrefixes: string[];
  center: { lat: number; lng: number };
  radiusKm: number;
  description: string;
}

// ─── Chandigarh Tricity ──────────────────────────────────────────────────────
// All sub-areas fall under prefix-4: ttqw
// Neighbors: ttqx, ttqz, ttqy, ttqv, ttqt, ttqm, ttqq, ttqr

export const CHANDIGARH_AREAS: AreaConfig[] = [
  {
    slug: "chandigarh",
    name: "Chandigarh Tricity",
    city: "Chandigarh Tricity",
    // City-wide: prefix-4 + key neighbors to catch edge listings
    geohashPrefixes: ["ttqw", "ttqx", "ttqt", "ttqq", "ttqr", "ttqv"],
    center: { lat: 30.7333, lng: 76.7794 },
    radiusKm: 30,
    description: "Browse rental listings across Chandigarh, Mohali, Kharar, Panchkula, Zirakpur and Landran.",
  },
  {
    slug: "mohali",
    name: "Mohali",
    city: "Chandigarh Tricity",
    // ttqw9 (center) + adjacent cells
    geohashPrefixes: ["ttqw9", "ttqw8", "ttqwd", "ttqwc", "ttqw3", "ttqw6"],
    center: { lat: 30.7046, lng: 76.7179 },
    radiusKm: 8,
    description: "Find rentals in Mohali — property, vehicles, electronics and more near you.",
  },
  {
    slug: "kharar",
    name: "Kharar",
    city: "Chandigarh Tricity",
    // ttqwb (center) + adjacent cells
    geohashPrefixes: ["ttqwb", "ttqwc", "ttqw8", "ttqw9", "ttqw2", "ttqw3"],
    center: { lat: 30.7460, lng: 76.6486 },
    radiusKm: 6,
    description: "Discover rental listings in Kharar — property, vehicles, equipment and more.",
  },
  {
    slug: "panchkula",
    name: "Panchkula",
    city: "Chandigarh Tricity",
    // ttqwt (center) + adjacent cells
    geohashPrefixes: ["ttqwt", "ttqws", "ttqww", "ttqwe", "ttqwg", "ttqwk"],
    center: { lat: 30.6942, lng: 76.8606 },
    radiusKm: 8,
    description: "Explore rentals in Panchkula — flats, PGs, vehicles and more.",
  },
  {
    slug: "zirakpur",
    name: "Zirakpur",
    city: "Chandigarh Tricity",
    // ttqw7 (center) + adjacent cells
    geohashPrefixes: ["ttqw7", "ttqw6", "ttqwe", "ttqwk", "ttqw4", "ttqw5"],
    center: { lat: 30.6434, lng: 76.8085 },
    radiusKm: 6,
    description: "Rent property, vehicles and equipment in Zirakpur on the map.",
  },
  {
    slug: "landran",
    name: "Landran",
    city: "Chandigarh Tricity",
    // ttqw6 (center) + adjacent cells
    geohashPrefixes: ["ttqw6", "ttqw7", "ttqw3", "ttqw4", "ttqw9", "ttqwd"],
    center: { lat: 30.6649, lng: 76.7652 },
    radiusKm: 5,
    description: "Browse rental listings in Landran — near Chandigarh University and beyond.",
  },
];

// ─── Ludhiana ────────────────────────────────────────────────────────────────
// All sub-areas fall under prefix-4: ttmz
// Neighbors: tttb, ttw0, ttqp, ttqn, ttmy, ttmw, ttmx, ttt8

export const LUDHIANA_AREAS: AreaConfig[] = [
  {
    slug: "ludhiana",
    name: "Ludhiana",
    city: "Ludhiana",
    // City-wide: prefix-4 + key neighbors
    geohashPrefixes: ["ttmz", "ttqn", "ttqp", "ttmy", "tttb", "ttt8"],
    center: { lat: 30.9010, lng: 75.8573 },
    radiusKm: 15,
    description: "Browse rental listings across Ludhiana — property, vehicles, electronics and more.",
  },
  {
    slug: "sarabha-nagar",
    name: "Sarabha Nagar",
    city: "Ludhiana",
    // ttmzv (center) + adjacent cells
    geohashPrefixes: ["ttmzv", "ttmzy", "ttmzt", "ttmzw", "ttmzs", "ttmzu"],
    center: { lat: 30.8967, lng: 75.8283 },
    radiusKm: 3,
    description: "Find rentals in Sarabha Nagar, Ludhiana — premium location listings.",
  },
  {
    slug: "model-town",
    name: "Model Town",
    city: "Ludhiana",
    // ttmzv (same cell as Sarabha Nagar — they're close)
    geohashPrefixes: ["ttmzv", "ttmzy", "ttmzw", "ttmzt", "ttmzs", "ttmzx"],
    center: { lat: 30.9110, lng: 75.8481 },
    radiusKm: 3,
    description: "Explore rental listings in Model Town, Ludhiana — flats, shops, vehicles.",
  },
  {
    slug: "pakhowal-road",
    name: "Pakhowal Road",
    city: "Ludhiana",
    // ttmzt (center) + adjacent cells
    geohashPrefixes: ["ttmzt", "ttmzv", "ttmzw", "ttmzs", "ttmze", "ttmzm"],
    center: { lat: 30.8890, lng: 75.8320 },
    radiusKm: 4,
    description: "Discover rentals along Pakhowal Road, Ludhiana — all categories.",
  },
  {
    slug: "brs-nagar",
    name: "BRS Nagar",
    city: "Ludhiana",
    // ttmzv (same cell as Sarabha Nagar)
    geohashPrefixes: ["ttmzv", "ttmzt", "ttmzy", "ttmzs", "ttmzu", "ttmzw"],
    center: { lat: 30.9012, lng: 75.8178 },
    radiusKm: 3,
    description: "Browse rentals in BRS Nagar, Ludhiana — property and more.",
  },
  {
    slug: "focal-point",
    name: "Focal Point",
    city: "Ludhiana",
    // ttmzw (center) + adjacent cells
    geohashPrefixes: ["ttmzw", "ttmzx", "ttmzy", "ttmzv", "ttmzt", "ttmzq"],
    center: { lat: 30.8850, lng: 75.8890 },
    radiusKm: 4,
    description: "Find commercial and residential rentals in Focal Point, Ludhiana.",
  },
];

// ─── Lookup Helpers ──────────────────────────────────────────────────────────


// ─── Delhi ───────────────────────────────────────────────────────────────────

export const DELHI_AREAS: AreaConfig[] = [
  {
    slug: "delhi",
    name: "Delhi",
    city: "Delhi",
    geohashPrefixes: ["ttn", "ttq", "tts"],
    center: { lat: 28.6139, lng: 77.2090 },
    radiusKm: 30,
    description: "Browse rental listings across Delhi — PG, rooms, flats, vehicles and more.",
  },
  {
    slug: "mukherjee-nagar",
    name: "Mukherjee Nagar",
    city: "Delhi",
    geohashPrefixes: ["tts5", "tts7", "ttse", "ttsk", "ttng", "ttnf"],
    center: { lat: 28.7007, lng: 77.2059 },
    radiusKm: 3,
    description: "Find PG, rooms and rentals in Mukherjee Nagar — Delhi's top student and UPSC hub.",
  },
  {
    slug: "gtb-nagar",
    name: "GTB Nagar",
    city: "Delhi",
    geohashPrefixes: ["tts5", "tts7", "ttse"],
    center: { lat: 28.6982, lng: 77.2058 },
    radiusKm: 2.5,
    description: "Explore rentals in GTB Nagar near Delhi University North Campus.",
  },
  {
    slug: "hudson-lane",
    name: "Hudson Lane",
    city: "Delhi",
    geohashPrefixes: ["tts5", "tts7"],
    center: { lat: 28.6964, lng: 77.2050 },
    radiusKm: 2,
    description: "Browse PGs, rooms and flats in Hudson Lane — popular student hotspot.",
  },
  {
    slug: "dwarka",
    name: "Dwarka",
    city: "Delhi",
    geohashPrefixes: ["ttnq", "ttnr", "ttnw", "ttnx"],
    center: { lat: 28.5921, lng: 77.0460 },
    radiusKm: 8,
    description: "Find rental properties in Dwarka — flats, homes and more.",
  },
  {
    slug: "rohini",
    name: "Rohini",
    city: "Delhi",
    geohashPrefixes: ["ttnh", "ttnj", "ttnn", "ttnp"],
    center: { lat: 28.7494, lng: 77.0562 },
    radiusKm: 7,
    description: "Explore rentals in Rohini — affordable housing and family homes.",
  },
  {
    slug: "jasola",
    name: "Jasola",
    city: "Delhi",
    geohashPrefixes: ["ttq4", "ttq5", "ttq6"],
    center: { lat: 28.5450, lng: 77.2910 },
    radiusKm: 4,
    description: "Find rentals in Jasola — office-linked and residential demand hub.",
  },
  {
    slug: "sarita-vihar",
    name: "Sarita Vihar",
    city: "Delhi",
    geohashPrefixes: ["ttq4", "ttq5"],
    center: { lat: 28.5315, lng: 77.2913 },
    radiusKm: 4,
    description: "Browse rentals in Sarita Vihar — flats, PGs and family homes.",
  },
];

// ─── Jaipur ───────────────────────────────────────────────────────────────────
export const JAIPUR_AREAS: AreaConfig[] = [
  {
    slug: "jaipur-metro",
    name: "Jaipur Metro",
    city: "Jaipur",
    geohashPrefixes: ["tsvc", "tsvb", "tsvf", "tsv8", "tsv9", "tsvd", "tsy1", "tsy0"],
    center: { lat: 26.9124, lng: 75.7873 },
    radiusKm: 25,
    description: "Browse rental listings across Greater Jaipur.",
  },
  {
    slug: "vaishali-nagar",
    name: "Vaishali Nagar",
    city: "Jaipur",
    geohashPrefixes: ["tsvbu", "tsvbv", "tsvbup", "tsvbut", "tsvbs", "tsvbw"],
    center: { lat: 26.8829, lng: 75.7885 },
    radiusKm: 4,
    description: "Rentals in Vaishali Nagar — flats, PG and family homes.",
  },
  {
    slug: "malviya-nagar",
    name: "Malviya Nagar",
    city: "Jaipur",
    geohashPrefixes: ["tsvbv", "tsvbw", "tsvbv0", "tsvbu", "tsvbs"],
    center: { lat: 26.8554, lng: 75.8094 },
    radiusKm: 5,
    description: "PG, rooms and flats near MNIT and WTP, Jaipur.",
  },
  {
    slug: "mansarovar",
    name: "Mansarovar",
    city: "Jaipur",
    geohashPrefixes: ["tsvbup", "tsvbu", "tsvbm", "tsvbs", "tsvbv"],
    center: { lat: 26.8908, lng: 75.7671 },
    radiusKm: 6,
    description: "Flats and PG across Mansarovar, Jaipur.",
  },
  {
    slug: "jagatpura",
    name: "Jagatpura",
    city: "Jaipur",
    geohashPrefixes: ["tsvbwe", "tsvbw", "tsvbm", "tsvbh", "tsvbn"],
    center: { lat: 26.8267, lng: 75.8777 },
    radiusKm: 5,
    description: "Jagatpura and Sitapura corridor rentals.",
  },
  {
    slug: "c-scheme",
    name: "C-Scheme",
    city: "Jaipur",
    geohashPrefixes: ["tsvcj5", "tsvcj", "tsvcj6", "tsvch", "tsvck"],
    center: { lat: 26.9155, lng: 75.8069 },
    radiusKm: 3,
    description: "Central Jaipur — C-Scheme and MI Road rentals.",
  },
  {
    slug: "raja-park",
    name: "Raja Park",
    city: "Jaipur",
    geohashPrefixes: ["tsvcj6", "tsvcj", "tsvch", "tsvck", "tsvcm"],
    center: { lat: 26.9059, lng: 75.8192 },
    radiusKm: 3,
    description: "Raja Park and central colony rentals.",
  },
  {
    slug: "sitapura",
    name: "Sitapura",
    city: "Jaipur",
    geohashPrefixes: ["tsvbmf", "tsvbm", "tsvbk", "tsvbj", "tsvbh"],
    center: { lat: 26.7758, lng: 75.8456 },
    radiusKm: 6,
    description: "Sitapura industrial and student belt rentals.",
  },
  {
    slug: "tonk-road",
    name: "Tonk Road",
    city: "Jaipur",
    geohashPrefixes: ["tsvbsw", "tsvbs", "tsvbt", "tsvbu", "tsvbq"],
    center: { lat: 26.8434, lng: 75.7936 },
    radiusKm: 5,
    description: "Tonk Road and Durgapura corridor rentals.",
  },
  {
    slug: "bani-park",
    name: "Bani Park",
    city: "Jaipur",
    geohashPrefixes: ["tsvchw", "tsvch", "tsvcj", "tsvcn", "tsvcp"],
    center: { lat: 26.9319, lng: 75.7897 },
    radiusKm: 4,
    description: "Bani Park and station-area rentals.",
  },
  {
    slug: "vidhyadhar-nagar",
    name: "Vidhyadhar Nagar",
    city: "Jaipur",
    geohashPrefixes: ["tsvcn", "tsvcp", "tsvcq", "tsvcj", "tsvcm"],
    center: { lat: 26.9981, lng: 75.786 },
    radiusKm: 5,
    description: "Vidhyadhar Nagar — planned sector flats and family homes.",
  },
];

// ─── Noida ────────────────────────────────────────────────────────────────────
export const NOIDA_AREAS: AreaConfig[] = [
  {
    slug: "noida-metro",
    name: "Noida Metro",
    city: "Noida",
    geohashPrefixes: ["ttq4", "ttq5", "ttq6", "ttng", "ttnf", "ttne", "ttnh"],
    center: { lat: 28.5355, lng: 77.391 },
    radiusKm: 22,
    description: "Browse rental listings across Noida and Greater Noida.",
  },
  {
    slug: "sector-62",
    name: "Sector 62",
    city: "Noida",
    geohashPrefixes: ["ttng", "ttnh", "ttnj", "ttnn", "ttnk"],
    center: { lat: 28.627, lng: 77.3649 },
    radiusKm: 4,
    description: "PG, flats and IT-corridor rentals in Sector 62, Noida.",
  },
  {
    slug: "sector-18",
    name: "Sector 18",
    city: "Noida",
    geohashPrefixes: ["ttq4", "ttq5", "ttq6", "ttq1", "ttq3"],
    center: { lat: 28.5708, lng: 77.3261 },
    radiusKm: 4,
    description: "Metro-linked flats and PG in Sector 18, Noida.",
  },
  {
    slug: "sector-50",
    name: "Sector 50",
    city: "Noida",
    geohashPrefixes: ["ttq5", "ttq6", "ttq4", "ttq7", "ttq3"],
    center: { lat: 28.5745, lng: 77.356 },
    radiusKm: 4,
    description: "Society flats and family rentals in Sector 50, Noida.",
  },
  {
    slug: "sector-76",
    name: "Sector 76",
    city: "Noida",
    geohashPrefixes: ["ttq7", "ttq6", "ttq5", "ttqe", "ttqd"],
    center: { lat: 28.6045, lng: 77.387 },
    radiusKm: 5,
    description: "Noida West and Aqua Line corridor rentals.",
  },
  {
    slug: "sector-137",
    name: "Sector 137",
    city: "Noida",
    geohashPrefixes: ["ttq6", "ttq3", "ttq2", "ttq8", "ttq9"],
    center: { lat: 28.5022, lng: 77.4118 },
    radiusKm: 5,
    description: "Expressway corridor flats in Sector 137, Noida.",
  },
  {
    slug: "sector-15",
    name: "Sector 15",
    city: "Noida",
    geohashPrefixes: ["ttq1", "ttq3", "ttq4", "ttq0", "ttq2"],
    center: { lat: 28.585, lng: 77.3115 },
    radiusKm: 4,
    description: "Old Noida family flats and builder floors.",
  },
  {
    slug: "sector-128",
    name: "Sector 128",
    city: "Noida",
    geohashPrefixes: ["ttq5", "ttq4", "ttq6", "ttq7", "ttq3"],
    center: { lat: 28.535, lng: 77.365 },
    radiusKm: 4,
    description: "Jaypee Wish Town and Sector 128 premium rentals.",
  },
  {
    slug: "greater-noida",
    name: "Greater Noida",
    city: "Noida",
    geohashPrefixes: ["ttq9", "ttq8", "ttqc", "ttqb", "ttqd"],
    center: { lat: 28.4744, lng: 77.504 },
    radiusKm: 12,
    description: "Flats and PG across Greater Noida sectors.",
  },
  {
    slug: "noida-extension",
    name: "Noida Extension",
    city: "Noida",
    geohashPrefixes: ["ttqe", "ttqd", "ttq7", "ttq6", "ttqs"],
    center: { lat: 28.613, lng: 77.42 },
    radiusKm: 8,
    description: "Greater Noida West and Noida Extension society flats.",
  },
  {
    slug: "sector-45",
    name: "Sector 45",
    city: "Noida",
    geohashPrefixes: ["ttq5", "ttq6", "ttq4", "ttq3", "ttq7"],
    center: { lat: 28.554, lng: 77.352 },
    radiusKm: 4,
    description: "Central Noida family rentals in Sector 45.",
  },
];

// ─── Lucknow ─────────────────────────────────────────────────────────────────
export const LUCKNOW_AREAS: AreaConfig[] = [
  {
    slug: "lucknow-metro",
    name: "Lucknow Metro",
    city: "Lucknow",
    geohashPrefixes: ["tuc8", "tuc9", "tucb", "tucc", "tuc2", "tuc3", "tu9z"],
    center: { lat: 26.8467, lng: 80.9462 },
    radiusKm: 22,
    description: "Browse rental listings across Lucknow.",
  },
  {
    slug: "gomti-nagar",
    name: "Gomti Nagar",
    city: "Lucknow",
    geohashPrefixes: ["tuc8ep", "tuc8e", "tuc8f", "tuc8g", "tuc8d"],
    center: { lat: 26.8486, lng: 80.9975 },
    radiusKm: 5,
    description: "Gomti Nagar and Extension apartment rentals.",
  },
  {
    slug: "indira-nagar-lucknow",
    name: "Indira Nagar",
    city: "Lucknow",
    geohashPrefixes: ["tuc8fw", "tuc8f", "tuc8e", "tuc9", "tuc91"],
    center: { lat: 26.8856, lng: 80.9778 },
    radiusKm: 4,
    description: "Indira Nagar and Faizabad Road PG and flats.",
  },
  {
    slug: "aliganj",
    name: "Aliganj",
    city: "Lucknow",
    geohashPrefixes: ["tuc91y", "tuc91", "tuc90", "tuc92", "tuc8"],
    center: { lat: 26.9319, lng: 80.9463 },
    radiusKm: 4,
    description: "Aliganj student and PG rental belt.",
  },
  {
    slug: "hazratganj",
    name: "Hazratganj",
    city: "Lucknow",
    geohashPrefixes: ["tuc8f0", "tuc8f", "tuc8e", "tuc8d", "tuc8c"],
    center: { lat: 26.8543, lng: 80.948 },
    radiusKm: 3,
    description: "CBD Hazratganj and Janpath corridor rentals.",
  },
  {
    slug: "aashiana",
    name: "Aashiana",
    city: "Lucknow",
    geohashPrefixes: ["tuc82u", "tuc82", "tuc83", "tuc80", "tuc8"],
    center: { lat: 26.7896, lng: 80.8964 },
    radiusKm: 6,
    description: "Aashiana and Sultanpur Road new townships.",
  },
  {
    slug: "mahanagar",
    name: "Mahanagar",
    city: "Lucknow",
    geohashPrefixes: ["tuc8fq", "tuc8f", "tuc8g", "tuc8e", "tuc8k"],
    center: { lat: 26.888, lng: 80.962 },
    radiusKm: 4,
    description: "Mahanagar and Nishatganj flats.",
  },
  {
    slug: "kapoorthala",
    name: "Kapoorthala",
    city: "Lucknow",
    geohashPrefixes: ["tuc8fe", "tuc8f", "tuc91", "tuc90", "tuc8"],
    center: { lat: 26.8712, lng: 80.978 },
    radiusKm: 3,
    description: "Kapoorthala and Kursi Road budget rentals.",
  },
  {
    slug: "vikas-nagar",
    name: "Vikas Nagar",
    city: "Lucknow",
    geohashPrefixes: ["tuc8fk", "tuc8f", "tuc8e", "tuc8g"],
    center: { lat: 26.8761, lng: 80.964 },
    radiusKm: 3,
    description: "Vikas Nagar family housing rentals.",
  },
  {
    slug: "jankipuram",
    name: "Jankipuram",
    city: "Lucknow",
    geohashPrefixes: ["tuc91w", "tuc91", "tuc90", "tuc93", "tuc9"],
    center: { lat: 26.9319, lng: 80.936 },
    radiusKm: 5,
    description: "Jankipuram sector-wise flats and PG.",
  },
];

// ─── Mumbai ──────────────────────────────────────────────────────────────────
export const MUMBAI_AREAS: AreaConfig[] = [
  {
    slug: "mumbai-metro",
    name: "Mumbai Metropolitan",
    city: "Mumbai",
    geohashPrefixes: ["te7u", "te7v", "te7g", "te7e", "te7s", "te7t", "tek5"],
    center: { lat: 19.076, lng: 72.8777 },
    radiusKm: 35,
    description: "Browse rental listings across Greater Mumbai MMR.",
  },
  {
    slug: "powai",
    name: "Powai",
    city: "Mumbai",
    geohashPrefixes: ["te7ug0", "te7ug", "te7uh", "te7uf", "te7u5"],
    center: { lat: 19.1174, lng: 72.9097 },
    radiusKm: 4,
    description: "Powai and Hiranandani rental hub.",
  },
  {
    slug: "andheri-west",
    name: "Andheri West",
    city: "Mumbai",
    geohashPrefixes: ["te7uc7", "te7uc", "te7ub", "te7u4", "te7u5"],
    center: { lat: 19.1364, lng: 72.8296 },
    radiusKm: 4,
    description: "Andheri West — Lokhandwala and Versova rentals.",
  },
  {
    slug: "bandra-west",
    name: "Bandra West",
    city: "Mumbai",
    geohashPrefixes: ["te7u3m", "te7u3", "te7u2", "te7u8", "te7u9"],
    center: { lat: 19.0596, lng: 72.8295 },
    radiusKm: 3,
    description: "Bandra West premium flats.",
  },
  {
    slug: "goregaon",
    name: "Goregaon",
    city: "Mumbai",
    geohashPrefixes: ["te7v18", "te7v1", "te7v0", "te7v4", "te7u"],
    center: { lat: 19.1642, lng: 72.8497 },
    radiusKm: 5,
    description: "Goregaon East and West tower rentals.",
  },
  {
    slug: "chembur",
    name: "Chembur",
    city: "Mumbai",
    geohashPrefixes: ["te7u6u", "te7u6", "te7u7", "te7u4", "te7u5"],
    center: { lat: 19.0522, lng: 72.8994 },
    radiusKm: 4,
    description: "Chembur eastern suburb rentals.",
  },
  {
    slug: "vashi",
    name: "Vashi",
    city: "Mumbai",
    geohashPrefixes: ["te7ut1", "te7ut", "te7uu", "te7us", "te7uk"],
    center: { lat: 19.0803, lng: 72.9947 },
    radiusKm: 5,
    description: "Vashi and Palm Beach Navi Mumbai rentals.",
  },
  {
    slug: "borivali",
    name: "Borivali",
    city: "Mumbai",
    geohashPrefixes: ["te7v3v", "te7v3", "te7v2", "te7v6", "te7v"],
    center: { lat: 19.2324, lng: 72.8565 },
    radiusKm: 6,
    description: "Borivali and Dahisar corridor flats.",
  },
  {
    slug: "mulund",
    name: "Mulund",
    city: "Mumbai",
    geohashPrefixes: ["te7vh4", "te7vh", "te7vj", "te7v5", "te7v7"],
    center: { lat: 19.1723, lng: 72.9565 },
    radiusKm: 4,
    description: "Mulund central line suburb rentals.",
  },
  {
    slug: "thane-west",
    name: "Thane West",
    city: "Mumbai",
    geohashPrefixes: ["te7vkd", "te7vk", "te7vj", "te7vm", "te7vq"],
    center: { lat: 19.2183, lng: 72.9781 },
    radiusKm: 7,
    description: "Thane West and Ghodbunder Road towers.",
  },
  {
    slug: "worli",
    name: "Worli",
    city: "Mumbai",
    geohashPrefixes: ["te7u15", "te7u1", "te7u0", "te7u4", "te7u5"],
    center: { lat: 19.0059, lng: 72.8176 },
    radiusKm: 3,
    description: "Worli and Lower Parel premium rentals.",
  },
];

// ─── London (UK) ─────────────────────────────────────────────────────────────
export const LONDON_AREAS: AreaConfig[] = [
  {
    slug: "greater-london",
    name: "Greater London",
    city: "London",
    geohashPrefixes: ["gcpv", "gcpu", "gcps", "gcpt", "gcpw", "gcpy", "gcpe", "gcpg"],
    center: { lat: 51.5074, lng: -0.1278 },
    radiusKm: 35,
    description: "Browse rental listings across Greater London.",
  },
  {
    slug: "camden",
    name: "Camden",
    city: "London",
    geohashPrefixes: ["gcpvh", "gcpvj", "gcpv5", "gcpv4", "gcpv6", "gcpv7"],
    center: { lat: 51.539, lng: -0.1426 },
    radiusKm: 4,
    description: "Find rentals in Camden and nearby.",
  },
  {
    slug: "islington",
    name: "Islington",
    city: "London",
    geohashPrefixes: ["gcpvj", "gcpvn", "gcpvp", "gcpv5", "gcpv7"],
    center: { lat: 51.541, lng: -0.104 },
    radiusKm: 4,
    description: "Rentals in Islington and Angel.",
  },
  {
    slug: "hackney",
    name: "Hackney",
    city: "London",
    geohashPrefixes: ["gcpvn", "gcpvp", "gcpvnx", "gcpvpb", "gcpvnc"],
    center: { lat: 51.545, lng: -0.055 },
    radiusKm: 4,
    description: "East London — Hackney and Dalston corridor.",
  },
  {
    slug: "tower-hamlets",
    name: "Tower Hamlets",
    city: "London",
    geohashPrefixes: ["gcpvp", "gcpvr", "gcpvpb", "gcpvpc", "gcpvp2"],
    center: { lat: 51.509, lng: -0.006 },
    radiusKm: 5,
    description: "Whitechapel, Isle of Dogs and Docklands.",
  },
  {
    slug: "southwark",
    name: "Southwark",
    city: "London",
    geohashPrefixes: ["gcpuv", "gcpuw", "gcpuvz", "gcpuvy", "gcpuvv"],
    center: { lat: 51.503, lng: -0.089 },
    radiusKm: 4,
    description: "Southwark and south bank corridor.",
  },
  {
    slug: "lambeth",
    name: "Lambeth",
    city: "London",
    geohashPrefixes: ["gcpuv", "gcpuu", "gcpuvq", "gcpuum", "gcpuuj"],
    center: { lat: 51.498, lng: -0.12 },
    radiusKm: 4,
    description: "Brixton, Vauxhall and Lambeth rentals.",
  },
  {
    slug: "westminster",
    name: "Westminster",
    city: "London",
    geohashPrefixes: ["gcpuu", "gcpug", "gcpuuy", "gcpugs", "gcpuuv"],
    center: { lat: 51.497, lng: -0.135 },
    radiusKm: 3,
    description: "Central Westminster and West End.",
  },
  {
    slug: "kensington-chelsea",
    name: "Kensington & Chelsea",
    city: "London",
    geohashPrefixes: ["gcpug", "gcpuf", "gcpugx", "gcpugz", "gcpufu"],
    center: { lat: 51.501, lng: -0.194 },
    radiusKm: 3,
    description: "RBKC — Kensington and Chelsea.",
  },
  {
    slug: "shoreditch",
    name: "Shoreditch",
    city: "London",
    geohashPrefixes: ["gcpvj", "gcpvn", "gcpvjw", "gcpvjq", "gcpvjx"],
    center: { lat: 51.5232, lng: -0.0872 },
    radiusKm: 2,
    description: "Shoreditch and Spitalfields.",
  },
  {
    slug: "canary-wharf",
    name: "Canary Wharf",
    city: "London",
    geohashPrefixes: ["gcpvp", "gcpvr", "gcpvp2", "gcpvp3", "gcpvrb"],
    center: { lat: 51.505, lng: -0.023 },
    radiusKm: 3,
    description: "Canary Wharf and Isle of Dogs.",
  },
];

// ─── Nairobi (Kenya) ─────────────────────────────────────────────────────────
export const NAIROBI_AREAS: AreaConfig[] = [
  {
    slug: "nairobi-metro",
    name: "Nairobi Metro",
    city: "Nairobi",
    geohashPrefixes: ["kzf0", "kzf1", "kzf2", "kzf3", "kzdr", "kzdp"],
    center: { lat: -1.286389, lng: 36.817223 },
    radiusKm: 25,
    description: "Browse rentals across the Nairobi metropolitan area.",
  },
  {
    slug: "westlands",
    name: "Westlands",
    city: "Nairobi",
    geohashPrefixes: ["kzf0v", "kzf0y", "kzf0w", "kzf0t", "kzf0u"],
    center: { lat: -1.267, lng: 36.81 },
    radiusKm: 4,
    description: "Westlands and Rhapta Road corridor.",
  },
  {
    slug: "kilimani",
    name: "Kilimani",
    city: "Nairobi",
    geohashPrefixes: ["kzf0t", "kzf0w", "kzf0th", "kzf0tk", "kzf0m"],
    center: { lat: -1.292, lng: 36.787 },
    radiusKm: 3,
    description: "Kilimani and Argwings Kodhek.",
  },
  {
    slug: "karen",
    name: "Karen",
    city: "Nairobi",
    geohashPrefixes: ["kzf07", "kzf0k", "kzf07r", "kzf0m", "kzf0q"],
    center: { lat: -1.32, lng: 36.71 },
    radiusKm: 6,
    description: "Karen and Langata south.",
  },
  {
    slug: "eastleigh",
    name: "Eastleigh",
    city: "Nairobi",
    geohashPrefixes: ["kzf0w", "kzf0x", "kzf0ww", "kzf0wx", "kzf0q"],
    center: { lat: -1.283, lng: 36.85 },
    radiusKm: 3,
    description: "Eastleigh commercial and residential.",
  },
  {
    slug: "south-b",
    name: "South B",
    city: "Nairobi",
    geohashPrefixes: ["kzf0w", "kzf0y", "kzf0w1", "kzf0wq", "kzf0x"],
    center: { lat: -1.31, lng: 36.83 },
    radiusKm: 3,
    description: "South B and South C corridor.",
  },
  {
    slug: "upper-hill",
    name: "Upper Hill",
    city: "Nairobi",
    geohashPrefixes: ["kzf0t", "kzf0e", "kzf0te", "kzf0s", "kzf0g"],
    center: { lat: -1.3, lng: 36.81 },
    radiusKm: 2,
    description: "Upper Hill business district.",
  },
  {
    slug: "parklands",
    name: "Parklands",
    city: "Nairobi",
    geohashPrefixes: ["kzf0v", "kzf0u", "kzf0vf", "kzf0ve", "kzf0y"],
    center: { lat: -1.26, lng: 36.82 },
    radiusKm: 3,
    description: "Parklands and Chiromo.",
  },
  {
    slug: "kasarani",
    name: "Kasarani",
    city: "Nairobi",
    geohashPrefixes: ["kzf1p", "kzf1r", "kzf1n", "kzf0x", "kzf1q"],
    center: { lat: -1.22, lng: 36.9 },
    radiusKm: 5,
    description: "Kasarani and Roysambu on Thika Road.",
  },
  {
    slug: "mombasa-road",
    name: "Mombasa Road",
    city: "Nairobi",
    geohashPrefixes: ["kzf0r", "kzf0x", "kzf0rp", "kzf0q", "kzf2"],
    center: { lat: -1.32, lng: 36.88 },
    radiusKm: 8,
    description: "Mombasa Road industrial and residential belt.",
  },
  {
    slug: "ngong-road",
    name: "Ngong Road",
    city: "Nairobi",
    geohashPrefixes: ["kzf0k", "kzf0m", "kzf0h", "kzf0j", "kzf07"],
    center: { lat: -1.32, lng: 36.745 },
    radiusKm: 5,
    description: "Ngong Road corridor toward Karen.",
  },
];

// ─── Lagos (Nigeria) ─────────────────────────────────────────────────────────
export const LAGOS_AREAS: AreaConfig[] = [
  {
    slug: "lagos-metro",
    name: "Lagos Metro",
    city: "Lagos",
    geohashPrefixes: ["s14m", "s14k", "s14s", "s14n", "s14j", "s14h"],
    center: { lat: 6.5244, lng: 3.3792 },
    radiusKm: 40,
    description: "Browse rentals across Greater Lagos.",
  },
  {
    slug: "lekki",
    name: "Lekki",
    city: "Lagos",
    geohashPrefixes: ["s14sc", "s14sb", "s14s9", "s14sd", "s14se"],
    center: { lat: 6.4698, lng: 3.5851 },
    radiusKm: 12,
    description: "Lekki peninsula and Ajah corridor.",
  },
  {
    slug: "ikeja",
    name: "Ikeja",
    city: "Lagos",
    geohashPrefixes: ["s14ms", "s14mu", "s14mt", "s14mv", "s14mm"],
    center: { lat: 6.6018, lng: 3.3515 },
    radiusKm: 6,
    description: "Ikeja GRA and Allen axis.",
  },
  {
    slug: "victoria-island",
    name: "Victoria Island",
    city: "Lagos",
    geohashPrefixes: ["s14kt", "s14ks", "s14ktf", "s14m5", "s14m4"],
    center: { lat: 6.4281, lng: 3.4219 },
    radiusKm: 4,
    description: "Victoria Island and Ozumba Mbadiwe.",
  },
  {
    slug: "yaba",
    name: "Yaba",
    city: "Lagos",
    geohashPrefixes: ["s14mh", "s14mj", "s14m7", "s14m6", "s14mk"],
    center: { lat: 6.5097, lng: 3.3717 },
    radiusKm: 3,
    description: "Yaba, Sabo and Tejuosho.",
  },
  {
    slug: "surulere",
    name: "Surulere",
    city: "Lagos",
    geohashPrefixes: ["s14ku", "s14kv", "s14kur", "s14ks", "s14kj"],
    center: { lat: 6.5005, lng: 3.3581 },
    radiusKm: 4,
    description: "Surulere mainland hub.",
  },
  {
    slug: "gbagada",
    name: "Gbagada",
    city: "Lagos",
    geohashPrefixes: ["s14mm", "s14mj", "s14mmh", "s14mk", "s14mq"],
    center: { lat: 6.5712, lng: 3.3915 },
    radiusKm: 4,
    description: "Gbagada and Ifako.",
  },
  {
    slug: "ajah",
    name: "Ajah",
    city: "Lagos",
    geohashPrefixes: ["s14sc", "s14t8", "s14scc", "s14sb", "s14t2"],
    center: { lat: 6.4683, lng: 3.6012 },
    radiusKm: 8,
    description: "Ajah and Sangotedo.",
  },
  {
    slug: "ikoyi",
    name: "Ikoyi",
    city: "Lagos",
    geohashPrefixes: ["s14kt", "s14ks", "s14kty", "s14kw", "s14kv"],
    center: { lat: 6.4531, lng: 3.4224 },
    radiusKm: 3,
    description: "Ikoyi and Osborne.",
  },
  {
    slug: "maryland",
    name: "Maryland",
    city: "Lagos",
    geohashPrefixes: ["s14mk", "s14m7", "s14mkt", "s14mj", "s14mh"],
    center: { lat: 6.5767, lng: 3.3656 },
    radiusKm: 3,
    description: "Maryland and Mende.",
  },
  {
    slug: "festac",
    name: "Festac",
    city: "Lagos",
    geohashPrefixes: ["s14kb", "s14m0", "s14jz", "s14jy", "s14m1"],
    center: { lat: 6.4709, lng: 3.2068 },
    radiusKm: 5,
    description: "Festac Town and Amuwo.",
  },
];

export const ALL_AREAS: AreaConfig[] = [
  ...CHANDIGARH_AREAS,
  ...LUDHIANA_AREAS,
  ...DELHI_AREAS,
  ...JAIPUR_AREAS,
  ...NOIDA_AREAS,
  ...LUCKNOW_AREAS,
  ...MUMBAI_AREAS,
  ...LONDON_AREAS,
  ...NAIROBI_AREAS,
  ...LAGOS_AREAS,
];

const CITY_HUB_ROW: Record<string, AreaConfig | undefined> = {
  chandigarh: CHANDIGARH_AREAS[0],
  ludhiana: LUDHIANA_AREAS[0],
  delhi: DELHI_AREAS[0],
  jaipur: JAIPUR_AREAS[0],
  noida: NOIDA_AREAS[0],
  lucknow: LUCKNOW_AREAS[0],
  mumbai: MUMBAI_AREAS[0],
  london: LONDON_AREAS[0],
  nairobi: NAIROBI_AREAS[0],
  lagos: LAGOS_AREAS[0],
};

export function getAreaConfig(citySlug: string, areaSlug?: string): AreaConfig | undefined {
  if (areaSlug) {
    return ALL_AREAS.find((a) => a.slug === areaSlug);
  }
  return CITY_HUB_ROW[citySlug];
}
