// Jaipur, Lucknow, Mumbai — city + area marketing pages (India /in/…)
import type { CityConfig } from "./rental-city-config-types";

export const JAIPUR_LUCKNOW_MUMBAI_CITIES: CityConfig[] = [
  {
    countrySlug: "in",
    slug: "jaipur",
    name: "Jaipur",
    country: "India",
    tagline: "Vaishali Nagar · Malviya Nagar · Mansarovar · Jagatpura · C-Scheme · Raja Park",
    badge: "NOW LIVE — JAIPUR",
    heroDescription:
      "Browse flats, PG, rooms, villas, vehicles and more on rent across Jaipur — Pink City, IT corridors and gated communities — on one live map. Contact listers directly on RentalPins.",
    coordinates: { lat: 26.9124, lng: 75.7873 },
    popularAreas: [
      "Vaishali Nagar", "Malviya Nagar", "Mansarovar", "Jagatpura", "C-Scheme",
      "Raja Park", "Sitapura", "Tonk Road", "Bani Park", "Vidhyadhar Nagar",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG, rooms, builder floors and independent houses across Jaipur’s top rental belts." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars, bikes and scooters for daily commute across Jaipur." },
      { name: "Electronics & Gadgets", color: "#FF8F00", icon: "💻", desc: "Laptops, AC on rent, appliances for students and working professionals." },
    ],
    popularSearches: [
      "PG in Malviya Nagar Jaipur", "Flat for rent Vaishali Nagar Jaipur",
      "Room for rent Mansarovar", "1 BHK Jagatpura", "2 BHK C Scheme Jaipur",
      "PG near Sitapura Jaipur", "Flat Tonk Road Jaipur", "Rent without broker Jaipur",
      "Apartment Raja Park", "Independent house Bani Park",
    ],
    faqs: [
      { q: "Which areas in Jaipur have the most flat and PG rentals?", a: "Malviya Nagar, Vaishali Nagar, Mansarovar and Jagatpura see very high demand from students and IT professionals. C-Scheme, Raja Park and Bani Park attract premium and family renters." },
      { q: "Is Sitapura good for student or budget PG?", a: "Sitapura and nearby industrial-education corridors host many PGs and budget rooms due to colleges and workplaces. Always verify distance to your campus or office on the map." },
      { q: "How do I list my Jaipur property on RentalPins?", a: "Download the RentalPins app, create your listing with photos and rent, and it appears on the live map for Jaipur." },
    ],
    ctaHeading: "Have something to rent in Jaipur?",
    ctaBody: "List your flat, PG, room or vehicle and reach renters across Vaishali Nagar, Malviya Nagar, Mansarovar and more. Free to list.",
    status: "live",
    areas: [
      {
        slug: "jaipur-metro",
        name: "Jaipur Metro",
        tagline: "Pink City · Outer ring · Sitapura corridor",
        badge: "JAIPUR — CITY WIDE",
        primaryFocus: "All rental categories",
        heroDescription: "Search live rental pins across Greater Jaipur — from Malviya and Vaishali to Jagatpura and Sitapura. Compare areas on the map before you message the lister.",
        coordinates: { lat: 26.9124, lng: 75.7873 },
        popularAreas: ["Central Jaipur", "South Jaipur", "East Jaipur", "Tonk corridor"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG and houses city-wide." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and bikes on rent." },
        ],
        popularSearches: ["Rentals Jaipur", "Flat rent Jaipur", "PG Jaipur"],
        faqs: [],
        ctaHeading: "Listing anywhere in Jaipur?",
        ctaBody: "Post from the RentalPins app.",
      },
      {
        slug: "vaishali-nagar",
        name: "Vaishali Nagar",
        tagline: "Nirman Nagar · Gandhi Path · Queens Road",
        badge: "NOW LIVE — VAISHALI NAGAR",
        primaryFocus: "Family flats & gated societies",
        heroDescription: "Vaishali Nagar is one of Jaipur’s strongest residential rental markets — modern apartments, builder floors and premium PG options.",
        coordinates: { lat: 26.8829, lng: 75.7885 },
        popularAreas: ["Vaishali Nagar", "Nirman Nagar", "Gandhi Path West", "Queens Road"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "2 & 3 BHK flats, builder floors and society apartments." },
          { name: "Furniture", color: "#5D4037", icon: "🛋️", desc: "Furniture packages for new tenants." },
        ],
        popularSearches: [
          "Flat for rent Vaishali Nagar Jaipur", "2 BHK Vaishali Nagar",
          "Society flat Vaishali Nagar", "PG Vaishali Nagar Jaipur",
        ],
        faqs: [{ q: "Why is Vaishali Nagar popular for rentals?", a: "Wide roads, gated communities, schools and retail make it a top choice for families and professionals commuting to Sitapura and central Jaipur." }],
        ctaHeading: "Renting out in Vaishali Nagar?",
        ctaBody: "List on RentalPins and appear on the map.",
      },
      {
        slug: "malviya-nagar",
        name: "Malviya Nagar",
        tagline: "WTP · MNIT · Airport Road",
        badge: "NOW LIVE — MALVIYA NAGAR",
        primaryFocus: "Students & IT renters",
        heroDescription: "Malviya Nagar combines universities, coaching and IT offices — huge demand for PG, single rooms and compact flats.",
        coordinates: { lat: 26.8554, lng: 75.8094 },
        popularAreas: ["Malviya Nagar", "JLN Marg", "Airport Road", "Gandhinagar Jaipur"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, rooms and 1 BHK flats near MNIT and WTP." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Bikes and scooters for student commute." },
        ],
        popularSearches: [
          "PG in Malviya Nagar Jaipur", "Room for rent Malviya Nagar",
          "Flat near MNIT Jaipur", "Hostel Malviya Nagar",
        ],
        faqs: [],
        ctaHeading: "PG or flat in Malviya Nagar?",
        ctaBody: "List free on RentalPins.",
      },
      {
        slug: "mansarovar",
        name: "Mansarovar",
        tagline: "New Sanganer Road · Shanthi Nagar · Gopalpura",
        badge: "NOW LIVE — MANSAROVAR",
        primaryFocus: "Affordable flats & PG",
        heroDescription: "Mansarovar is Jaipur’s largest planned residential zone — dense supply of flats, PG and family homes at multiple price points.",
        coordinates: { lat: 26.8908, lng: 75.7671 },
        popularAreas: ["Mansarovar", "Shanthi Nagar", "Patrakar Colony", "New Sanganer Road"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG and independent floors." },
        ],
        popularSearches: [
          "Flat for rent Mansarovar", "PG Mansarovar Jaipur",
          "1 BHK Mansarovar", "2 BHK New Sanganer Road",
        ],
        faqs: [],
        ctaHeading: "Mansarovar landlord?",
        ctaBody: "Reach thousands of renters on the map.",
      },
      {
        slug: "jagatpura",
        name: "Jagatpura",
        tagline: "IT SEZ · SKIT · Ramchandrapura",
        badge: "NOW LIVE — JAGATPURA",
        primaryFocus: "IT professionals & students",
        heroDescription: "Jagatpura links Sitapura industry, colleges and newer apartment supply — ideal for IT and student rentals.",
        coordinates: { lat: 26.8267, lng: 75.8777 },
        popularAreas: ["Jagatpura", "Ramchandrapura", "Mahapura", "Sitapura link"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Apartments and PG near IT and education hubs." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Small office and co-working where listed." },
        ],
        popularSearches: [
          "Flat Jagatpura Jaipur", "PG Jagatpura", "Rent near Sitapura Jaipur",
        ],
        faqs: [],
        ctaHeading: "Jagatpura lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "c-scheme",
        name: "C-Scheme",
        tagline: "MI Road · Statue Circle · Ashok Nagar",
        badge: "NOW LIVE — C-SCHEME",
        primaryFocus: "Premium central rentals",
        heroDescription: "C-Scheme and MI Road — premium apartments, offices and short-stay demand near central Jaipur.",
        coordinates: { lat: 26.9155, lng: 75.8069 },
        popularAreas: ["C-Scheme", "MI Road", "Ashok Nagar", "Statue Circle"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Premium flats and builder floors." },
        ],
        popularSearches: [
          "Flat C Scheme Jaipur", "Office rent MI Road", "Apartment Ashok Nagar Jaipur",
        ],
        faqs: [],
        ctaHeading: "Central Jaipur rental?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "raja-park",
        name: "Raja Park",
        tagline: "Subhash Nagar · Shastri Nagar · Central Jaipur",
        badge: "NOW LIVE — RAJA PARK",
        primaryFocus: "Mixed PG & family",
        heroDescription: "Raja Park and nearby colonies — strong PG, room and family flat demand with quick access to old city and offices.",
        coordinates: { lat: 26.9059, lng: 75.8192 },
        popularAreas: ["Raja Park", "Subhash Nagar", "Shastri Nagar"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Rooms, PG and flats." },
        ],
        popularSearches: ["PG Raja Park Jaipur", "Flat Raja Park", "Room rent Raja Park"],
        faqs: [],
        ctaHeading: "Raja Park lister?",
        ctaBody: "Go live on RentalPins.",
      },
      {
        slug: "sitapura",
        name: "Sitapura",
        tagline: "Industrial Area · Colleges · SEZ corridor",
        badge: "NOW LIVE — SITAPURA",
        primaryFocus: "Budget PG & workers’ housing",
        heroDescription: "Sitapura hosts industry, logistics and education — high volume of budget PG, rooms and shared flats.",
        coordinates: { lat: 26.7758, lng: 75.8456 },
        popularAreas: ["Sitapura", "Riico", "Mahapura", "Chokhi Dhani corridor"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, rooms and worker housing." },
          { name: "Heavy equipment", color: "#5D4037", icon: "🏗️", desc: "Plant and machinery where listed." },
        ],
        popularSearches: [
          "PG Sitapura Jaipur", "Room rent Sitapura", "Flat near Riico Jaipur",
        ],
        faqs: [],
        ctaHeading: "Sitapura landlord?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "tonk-road",
        name: "Tonk Road",
        tagline: "Pratap Nagar · Durgapura · Sanganer",
        badge: "NOW LIVE — TONK ROAD",
        primaryFocus: "Corridor flats & retail",
        heroDescription: "Tonk Road and Durgapura belt — apartments, shops on rent and family housing along the south corridor.",
        coordinates: { lat: 26.8434, lng: 75.7936 },
        popularAreas: ["Tonk Road", "Durgapura", "Pratap Nagar", "Sanganer"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and retail frontages." },
        ],
        popularSearches: ["Flat Tonk Road Jaipur", "Shop rent Tonk Road", "Durgapura flat"],
        faqs: [],
        ctaHeading: "Tonk Road lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "bani-park",
        name: "Bani Park",
        tagline: "Station · Collectorate · Heritage hotels",
        badge: "NOW LIVE — BANI PARK",
        primaryFocus: "Guest houses & mid-premium",
        heroDescription: "Bani Park — mix of heritage stays, service apartments and residential rentals near the railway station.",
        coordinates: { lat: 26.9319, lng: 75.7897 },
        popularAreas: ["Bani Park", "Civil Lines", "Hasanpura"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, guest-house style units and family homes." },
        ],
        popularSearches: ["Flat Bani Park Jaipur", "Service apartment Bani Park", "Near station Jaipur rent"],
        faqs: [],
        ctaHeading: "Bani Park lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "vidhyadhar-nagar",
        name: "Vidhyadhar Nagar",
        tagline: "Sector blocks · North Jaipur · Gandhi Path",
        badge: "NOW LIVE — VIDHYADHAR NAGAR",
        primaryFocus: "Planned sectors & society flats",
        heroDescription: "Vidhyadhar Nagar — planned residential sectors with society flats, builder floors and strong family rental demand in north Jaipur.",
        coordinates: { lat: 26.9981, lng: 75.786 },
        popularAreas: ["Vidhyadhar Nagar", "Sector 1", "Sector 6", "Gandhi Path north"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Society flats and builder floors." },
        ],
        popularSearches: [
          "Flat Vidhyadhar Nagar Jaipur", "2 BHK Vidhyadhar Nagar",
          "Society flat north Jaipur", "Rent Vidhyadhar Nagar",
        ],
        faqs: [
          {
            q: "Why is Vidhyadhar Nagar popular for family rentals?",
            a: "Planned sectors, newer societies and road infrastructure attract families comparing value with Vaishali Nagar and Mansarovar.",
          },
        ],
        ctaHeading: "Vidhyadhar Nagar lister?",
        ctaBody: "List on RentalPins.",
      },
    ],
  },
  {
    countrySlug: "in",
    slug: "lucknow",
    name: "Lucknow",
    country: "India",
    tagline: "Gomti Nagar · Indira Nagar · Aliganj · Hazratganj · Aashiana · Mahanagar",
    badge: "NOW LIVE — LUCKNOW",
    heroDescription:
      "Find PG, flats, independent houses, vehicles and more on rent across Lucknow — Gomti extension, student belts and metro-linked corridors — on RentalPins.",
    coordinates: { lat: 26.8467, lng: 80.9462 },
    popularAreas: [
      "Gomti Nagar", "Indira Nagar", "Aliganj", "Hazratganj", "Aashiana",
      "Mahanagar", "Kapoorthala", "Vikas Nagar", "Jankipuram", "Chinhat",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, rooms, flats and villas across Lucknow’s main rental corridors." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars, bikes and scooters for city commute." },
      { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Retail and office units in CBD and extension areas." },
    ],
    popularSearches: [
      "PG in Gomti Nagar Lucknow", "Flat for rent Indira Nagar Lucknow",
      "Room rent Aliganj", "1 BHK Gomti Nagar Extension",
      "Flat Hazratganj Lucknow", "PG near metro Lucknow",
      "House rent Aashiana", "Apartment Mahanagar Lucknow",
    ],
    faqs: [
      { q: "Which Lucknow areas are best for PG and student rentals?", a: "Indira Nagar, Aliganj, Kapoorthala and Jankipuram see strong PG and room demand. Gomti Nagar and Extension attract professionals and families." },
      { q: "Is Gomti Nagar Extension good for 2 BHK flats?", a: "Yes — Gomti Nagar and Gomti Nagar Extension have a large supply of new apartments and society flats; use the map to compare micro-locations." },
    ],
    ctaHeading: "Have something to rent in Lucknow?",
    ctaBody: "List your PG, flat or vehicle and reach renters across Gomti Nagar, Indira Nagar, Aliganj and more.",
    status: "live",
    areas: [
      {
        slug: "lucknow-metro",
        name: "Lucknow Metro",
        tagline: "Gomti belt · Old city link · Airport corridor",
        badge: "LUCKNOW — CITY WIDE",
        primaryFocus: "All categories",
        heroDescription: "Browse rental listings across Lucknow — from Gomti and Indira Nagar to Aliganj and Aashiana — on one map.",
        coordinates: { lat: 26.8467, lng: 80.9462 },
        popularAreas: ["East Lucknow", "Central", "South", "Metro corridor"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG city-wide." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and bikes." },
        ],
        popularSearches: ["Rent Lucknow", "Flat Lucknow", "PG Lucknow"],
        faqs: [],
        ctaHeading: "Listing in Lucknow?",
        ctaBody: "Post from the RentalPins app.",
      },
      {
        slug: "gomti-nagar",
        name: "Gomti Nagar",
        tagline: "Extension · Vijay Khand · Patrakarpuram",
        badge: "NOW LIVE — GOMTI NAGAR",
        primaryFocus: "Premium flats & offices",
        heroDescription: "Gomti Nagar and Extension — Lucknow’s premium apartment market, professionals and retail-linked rentals.",
        coordinates: { lat: 26.8486, lng: 80.9975 },
        popularAreas: ["Gomti Nagar", "Gomti Nagar Extension", "Patrakarpuram", "Vijay Khand"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "2–4 BHK society flats and builder floors." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Office and retail on main corridors." },
        ],
        popularSearches: [
          "Flat Gomti Nagar Lucknow", "2 BHK Gomti Nagar Extension",
          "PG Gomti Nagar", "Apartment Patrakarpuram",
        ],
        faqs: [],
        ctaHeading: "Gomti Nagar landlord?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "indira-nagar-lucknow",
        name: "Indira Nagar",
        tagline: "Faizabad Road · Munshipulia · Metro",
        badge: "NOW LIVE — INDIRA NAGAR",
        primaryFocus: "PG & family flats",
        heroDescription: "Indira Nagar — high PG density, metro access and mix of affordable flats along Faizabad Road.",
        coordinates: { lat: 26.8856, lng: 80.9778 },
        popularAreas: ["Indira Nagar", "Munshipulia", "Khurram Nagar"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, rooms and flats." },
        ],
        popularSearches: [
          "PG Indira Nagar Lucknow", "Flat Indira Nagar Lucknow",
          "Room rent Munshipulia",
        ],
        faqs: [],
        ctaHeading: "Indira Nagar lister?",
        ctaBody: "Go live on RentalPins.",
      },
      {
        slug: "aliganj",
        name: "Aliganj",
        tagline: "Lucknow University · CDRI · Kapoorthala",
        badge: "NOW LIVE — ALIGANJ",
        primaryFocus: "Student & academic belt",
        heroDescription: "Aliganj — classic student and academic rental belt with strong PG and room demand.",
        coordinates: { lat: 26.9319, lng: 80.9463 },
        popularAreas: ["Aliganj", "Sector L", "Sector K", "University area"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, rooms and shared flats." },
          { name: "Furniture", color: "#5D4037", icon: "🛋️", desc: "Student furniture on rent." },
        ],
        popularSearches: ["PG Aliganj Lucknow", "Room Aliganj", "Flat near Lucknow University"],
        faqs: [],
        ctaHeading: "Aliganj PG owner?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "hazratganj",
        name: "Hazratganj & CBD",
        tagline: "Janpath · MG Marg · Husainganj",
        badge: "NOW LIVE — HAZRATGANJ",
        primaryFocus: "CBD apartments & retail",
        heroDescription: "Hazratganj and central CBD — offices, retail and premium apartments with strong walk-to-work demand.",
        coordinates: { lat: 26.8543, lng: 80.948 },
        popularAreas: ["Hazratganj", "Janpath", "Husainganj", "Lalbagh"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Central flats and service apartments." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "CBD office and shop rentals." },
        ],
        popularSearches: [
          "Flat Hazratganj", "Office rent Janpath Lucknow", "Apartment CBD Lucknow",
        ],
        faqs: [],
        ctaHeading: "CBD Lucknow lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "aashiana",
        name: "Aashiana",
        tagline: "Sultanpur Road · Airport · Amar Shaheed Path",
        badge: "NOW LIVE — AASHIANA",
        primaryFocus: "New townships & families",
        heroDescription: "Aashiana and Sultanpur Road — newer townships, gated societies and airport-linked family demand.",
        coordinates: { lat: 26.7896, lng: 80.8964 },
        popularAreas: ["Aashiana", "Sultanpur Road", "Amar Shaheed Path"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Society flats and villas." },
        ],
        popularSearches: ["Flat Aashiana Lucknow", "2 BHK Sultanpur Road", "House rent near airport Lucknow"],
        faqs: [],
        ctaHeading: "Aashiana lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "mahanagar",
        name: "Mahanagar",
        tagline: "Nishatganj · Badshah Nagar · Metro north",
        badge: "NOW LIVE — MAHANAGAR",
        primaryFocus: "Mid-market apartments",
        heroDescription: "Mahanagar and Nishatganj — dense mid-market flats, PG and shops with good metro connectivity.",
        coordinates: { lat: 26.888, lng: 80.962 },
        popularAreas: ["Mahanagar", "Nishatganj", "Badshah Nagar"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG." },
        ],
        popularSearches: ["Flat Mahanagar Lucknow", "PG Nishatganj", "Room Badshah Nagar"],
        faqs: [],
        ctaHeading: "Mahanagar lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "kapoorthala",
        name: "Kapoorthala",
        tagline: "Aliganj link · Kursi Road",
        badge: "NOW LIVE — KAPOORTHALA",
        primaryFocus: "Rooms & budget flats",
        heroDescription: "Kapoorthala area — budget rooms, PG and flats linking Aliganj and northern corridors.",
        coordinates: { lat: 26.8712, lng: 80.978 },
        popularAreas: ["Kapoorthala", "Kursi Road", "Tedhi Pulia"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG and rooms." },
        ],
        popularSearches: ["PG Kapoorthala", "Room rent Kapoorthala Lucknow"],
        faqs: [],
        ctaHeading: "Kapoorthala lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "vikas-nagar",
        name: "Vikas Nagar",
        tagline: "Khurram Nagar · Ring Road east",
        badge: "NOW LIVE — VIKAS NAGAR",
        primaryFocus: "Family housing",
        heroDescription: "Vikas Nagar — residential blocks and independent houses with strong family rental demand.",
        coordinates: { lat: 26.8761, lng: 80.964 },
        popularAreas: ["Vikas Nagar", "Khurram Nagar", "Indira Nagar link"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and houses." },
        ],
        popularSearches: ["Flat Vikas Nagar Lucknow", "House Khurram Nagar"],
        faqs: [],
        ctaHeading: "Vikas Nagar lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "jankipuram",
        name: "Jankipuram",
        tagline: "Sector A–G · Kursi Road north",
        badge: "NOW LIVE — JANKIPURAM",
        primaryFocus: "Planned sectors & PG",
        heroDescription: "Jankipuram sectors — planned layouts, PG clusters and affordable flats along Kursi Road.",
        coordinates: { lat: 26.9319, lng: 80.936 },
        popularAreas: ["Jankipuram", "Sector A", "Sector F", "Kursi Road"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG by sector." },
        ],
        popularSearches: ["PG Jankipuram", "Flat Jankipuram Sector F", "Room Jankipuram Lucknow"],
        faqs: [],
        ctaHeading: "Jankipuram lister?",
        ctaBody: "Post on RentalPins.",
      },
    ],
  },
  {
    countrySlug: "in",
    slug: "mumbai",
    name: "Mumbai",
    country: "India",
    tagline: "Powai · Andheri · Bandra · Goregaon · Chembur · Navi Mumbai · Thane",
    badge: "NOW LIVE — MUMBAI",
    heroDescription:
      "Browse flats, PG, shared rooms, office-linked rentals and more across Mumbai and Navi Mumbai on RentalPins — India’s most competitive rental market, on one map.",
    coordinates: { lat: 19.076, lng: 72.8777 },
    popularAreas: [
      "Powai", "Andheri West", "Bandra West", "Goregaon", "Chembur",
      "Vashi", "Borivali", "Mulund", "Thane", "Worli",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG, paying guest, co-living and premium sea-facing pockets." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and bikes — high demand for weekend and commute rentals." },
      { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Retail, office and co-working in CBD and suburban hubs." },
    ],
    popularSearches: [
      "Flat for rent Powai", "PG Andheri West", "1 BHK Bandra West",
      "Flat Goregaon East", "Room rent Chembur", "2 BHK Vashi",
      "Flat Borivali West", "PG Mulund", "Flat Thane West", "Office Worli",
      "Rent without broker Mumbai",
    ],
    faqs: [
      { q: "Which Mumbai areas have the highest rental search volume?", a: "Suburban hubs like Andheri, Goregaon, Borivali, Powai, Chembur, Mulund and Thane see very high flat and PG queries. Bandra–Khar west and Worli skew premium. Navi Mumbai (Vashi, Nerul) attracts value-seeking professionals." },
      { q: "Does RentalPins cover Navi Mumbai?", a: "Yes — we include Vashi as a key Navi Mumbai rental hub; expand your map search to see pins across the wider MMR region as listings grow." },
    ],
    ctaHeading: "Have something to rent in Mumbai?",
    ctaBody: "List your flat, PG, room or desk space and reach renters across Powai, Andheri, Bandra and beyond.",
    status: "live",
    areas: [
      {
        slug: "mumbai-metro",
        name: "Mumbai Metropolitan",
        tagline: "Island City · Western suburbs · Harbour · Navi Mumbai",
        badge: "MUMBAI — CITY WIDE",
        primaryFocus: "All categories",
        heroDescription: "Greater Mumbai MMR — search live pins from South Mumbai to Thane and Navi Mumbai. Micro-markets vary sharply; use the map to shortlist.",
        coordinates: { lat: 19.076, lng: 72.8777 },
        popularAreas: ["Western Line", "Harbour Line", "Central suburbs", "Navi Mumbai"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG across MMR." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and bikes." },
        ],
        popularSearches: ["Rent Mumbai", "Flat Mumbai", "PG Mumbai"],
        faqs: [],
        ctaHeading: "Listing in MMR?",
        ctaBody: "Post from the RentalPins app.",
      },
      {
        slug: "powai",
        name: "Powai",
        tagline: "Hiranandani · IIT Bombay · JVLR",
        badge: "NOW LIVE — POWAI",
        primaryFocus: "IT & premium flats",
        heroDescription: "Powai — flagship IT and premium apartment demand around Hiranandani, IIT and JVLR.",
        coordinates: { lat: 19.1174, lng: 72.9097 },
        popularAreas: ["Hiranandani Gardens", "Chandivali", "JVLR", "Vikhroli Parksite"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Premium flats and PG for tech workforce." },
        ],
        popularSearches: ["Flat rent Powai", "PG Powai", "2 BHK Hiranandani Powai", "Shared flat Powai"],
        faqs: [],
        ctaHeading: "Powai lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "andheri-west",
        name: "Andheri West",
        tagline: "Lokhandwala · Versova · DN Nagar",
        badge: "NOW LIVE — ANDHERI WEST",
        primaryFocus: "Bollywood belt & young renters",
        heroDescription: "Andheri West — Lokhandwala, Versova and DN Nagar drive huge PG, 1 BHK and shared-flat search volume.",
        coordinates: { lat: 19.1364, lng: 72.8296 },
        popularAreas: ["Lokhandwala", "Versova", "Four Bungalows", "DN Nagar"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG and co-living pockets." },
        ],
        popularSearches: [
          "PG Andheri West", "Flat Lokhandwala", "1 BHK Versova", "Room Four Bungalows",
        ],
        faqs: [],
        ctaHeading: "Andheri West landlord?",
        ctaBody: "Reach renters on the map.",
      },
      {
        slug: "bandra-west",
        name: "Bandra West",
        tagline: "Linking Road · Pali Hill · Carter Road",
        badge: "NOW LIVE — BANDRA WEST",
        primaryFocus: "Premium sea-facing & creatives",
        heroDescription: "Bandra West — among India’s highest-intent premium rental micro-markets (Linking Road, Pali, Carter Road).",
        coordinates: { lat: 19.0596, lng: 72.8295 },
        popularAreas: ["Linking Road", "Pali Hill", "Carter Road", "Mount Mary"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Premium flats and jodi flats." },
        ],
        popularSearches: [
          "Flat Bandra West", "2 BHK Bandra Linking Road", "Sea facing rent Bandra",
        ],
        faqs: [],
        ctaHeading: "Bandra lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "goregaon",
        name: "Goregaon",
        tagline: "Film City · Aarey · Western Express",
        badge: "NOW LIVE — GOREGAON",
        primaryFocus: "Mid-market towers",
        heroDescription: "Goregaon East/West — high-rise supply, metro on Western Express and Film City employment pull.",
        coordinates: { lat: 19.1642, lng: 72.8497 },
        popularAreas: ["Goregaon East", "Goregaon West", "Film City", "Aarey"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Tower flats and PG." },
        ],
        popularSearches: ["Flat Goregaon East", "PG Goregaon West", "1 BHK near metro Goregaon"],
        faqs: [],
        ctaHeading: "Goregaon lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "chembur",
        name: "Chembur",
        tagline: "Eastern Express · Monorail · RCF",
        badge: "NOW LIVE — CHEMBUR",
        primaryFocus: "Eastern suburbs value",
        heroDescription: "Chembur — strong 1–2 BHK and PG demand with Monorail and Eastern Express connectivity.",
        coordinates: { lat: 19.0522, lng: 72.8994 },
        popularAreas: ["Chembur", "Tilak Nagar", "Kurla East link", "Govandi edge"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG." },
        ],
        popularSearches: ["Flat Chembur", "PG Chembur Mumbai", "2 BHK Chembur East"],
        faqs: [],
        ctaHeading: "Chembur lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "vashi",
        name: "Vashi & CBD Belapur corridor",
        tagline: "Palm Beach Road · Sector 17 · Turbhe",
        badge: "NOW LIVE — NAVI MUMBAI (VASHI)",
        primaryFocus: "IT offices & value flats",
        heroDescription: "Vashi — Navi Mumbai’s core commercial and residential node; huge search volume for flats near Palm Beach and CBD Belapur corridor.",
        coordinates: { lat: 19.0803, lng: 72.9947 },
        popularAreas: ["Vashi", "Sector 17", "Palm Beach", "Sanpada"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG for Navi Mumbai workforce." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "CBD office inventory where listed." },
        ],
        popularSearches: [
          "Flat Vashi", "PG Vashi Navi Mumbai", "2 BHK Palm Beach Road", "Rent CBD Belapur",
        ],
        faqs: [],
        ctaHeading: "Navi Mumbai lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "borivali",
        name: "Borivali",
        tagline: "National Park · Link Road · Dahisar",
        badge: "NOW LIVE — BORIVALI",
        primaryFocus: "Family towers & Metro-2A",
        heroDescription: "Borivali West/East — dense family flats, Metro 2A corridor and National Park adjacency.",
        coordinates: { lat: 19.2324, lng: 72.8565 },
        popularAreas: ["Borivali West", "Borivali East", "Kandivali link", "Dahisar"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Society flats and resale rental stock." },
        ],
        popularSearches: ["Flat Borivali West", "2 BHK Borivali East", "PG Borivali"],
        faqs: [],
        ctaHeading: "Borivali lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "mulund",
        name: "Mulund",
        tagline: "LBS Marg · Nahur · Airoli bridge",
        badge: "NOW LIVE — MULUND",
        primaryFocus: "Central suburb families",
        heroDescription: "Mulund — strong 2 BHK family demand, LBS Marg retail and quick Airoli/Navi Mumbai access.",
        coordinates: { lat: 19.1723, lng: 72.9565 },
        popularAreas: ["Mulund West", "Mulund East", "Nahur", "Bhandup link"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and duplexes." },
        ],
        popularSearches: ["Flat Mulund West", "2 BHK Mulund East", "Rent Nahur"],
        faqs: [],
        ctaHeading: "Mulund lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "thane-west",
        name: "Thane West",
        tagline: "Ghodbunder Road · Majiwada · Vartak Nagar",
        badge: "NOW LIVE — THANE WEST",
        primaryFocus: "New towers & Ghodbunder growth",
        heroDescription: "Thane West — explosive new supply on Ghodbunder Road; top Google cluster for “flat rent Thane”.",
        coordinates: { lat: 19.2183, lng: 72.9781 },
        popularAreas: ["Thane West", "Ghodbunder Road", "Majiwada", "Vartak Nagar"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "New towers and family flats." },
        ],
        popularSearches: [
          "Flat Thane West", "2 BHK Ghodbunder Road", "PG Thane Majiwada",
        ],
        faqs: [],
        ctaHeading: "Thane lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "worli",
        name: "Worli & Lower Parel",
        tagline: "High Street Phoenix · Peninsula · mill land",
        badge: "NOW LIVE — WORLI",
        primaryFocus: "Premium CBD & seaface",
        heroDescription: "Worli and Lower Parel — premium apartments, sea-view inventory and office-adjacent residential demand.",
        coordinates: { lat: 19.0059, lng: 72.8176 },
        popularAreas: ["Worli", "Lower Parel", "Prabhadevi", "Mahalaxmi"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Premium flats and sea-facing units." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Mill land offices nearby." },
        ],
        popularSearches: [
          "Flat Worli", "Sea facing Worli rent", "Apartment Lower Parel",
        ],
        faqs: [],
        ctaHeading: "South Mumbai lister?",
        ctaBody: "List on RentalPins.",
      },
    ],
  },
];
