// Noida — city + area marketing pages (India /in/…)
import type { CityConfig } from "./rental-city-config-types";

export const NOIDA_CITIES: CityConfig[] = [
  {
    countrySlug: "in",
    slug: "noida",
    name: "Noida",
    country: "India",
    tagline: "Sector 62 · Sector 18 · Sector 50 · Sector 137 · Greater Noida · Noida Extension",
    badge: "NOW LIVE — NOIDA",
    heroDescription:
      "Browse flats, PG, rooms, villas, vehicles and more on rent across Noida — IT corridors, metro-linked sectors and family societies — on one live map. Contact listers directly on RentalPins.",
    coordinates: { lat: 28.5355, lng: 77.391 },
    popularAreas: [
      "Sector 62", "Sector 18", "Sector 50", "Sector 76", "Sector 137",
      "Sector 15", "Sector 128", "Greater Noida", "Noida Extension", "Sector 45",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG, rooms, builder floors and society apartments across Noida sectors." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars, bikes and scooters for Noida–Delhi commute." },
      { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Office and co-working rentals along Noida Expressway and Sector 62." },
    ],
    popularSearches: [
      "PG in Sector 62 Noida", "Flat for rent Sector 18 Noida",
      "1 BHK Sector 50 Noida", "2 BHK Sector 137 Noida",
      "PG Greater Noida", "Flat Noida Extension",
      "Rent without broker Noida", "Society flat Sector 76",
    ],
    faqs: [
      { q: "Which Noida sectors have the most flat and PG rentals?", a: "Sector 62, Sector 18, Sector 50 and Sector 137 see very high demand from IT professionals and families. Greater Noida and Noida Extension attract value-focused renters." },
      { q: "Is Noida good for metro-linked rentals?", a: "Sectors along the Blue Line and Aqua Line corridors — including 18, 50, 76 and 137 — are popular for daily Delhi and NCR commutes. Use the map to verify pin distance to your station." },
      { q: "How do I list my Noida property on RentalPins?", a: "Post from the RentalPins app or web with photos and rent — your listing appears on the live Noida map for direct tenant contact." },
    ],
    ctaHeading: "Have something to rent in Noida?",
    ctaBody: "List your flat, PG, room or office and reach renters across Sector 62, Sector 18, Greater Noida and more.",
    status: "live",
    areas: [
      {
        slug: "noida-metro",
        name: "Noida Metro",
        tagline: "Expressway · Film City · Greater Noida corridor",
        badge: "NOIDA — CITY WIDE",
        primaryFocus: "All rental categories",
        heroDescription: "Search live rental pins across Noida and Greater Noida — from Sector 62 and 18 to 137 and Noida Extension. Compare sectors on the map before you message the lister.",
        coordinates: { lat: 28.5355, lng: 77.391 },
        popularAreas: ["Central Noida", "Expressway belt", "Greater Noida", "Noida Extension"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, PG and houses city-wide." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Offices along expressway corridors." },
        ],
        popularSearches: ["Rentals Noida", "Flat rent Noida", "PG Noida"],
        faqs: [],
        ctaHeading: "Listing anywhere in Noida?",
        ctaBody: "Post from the RentalPins app.",
      },
      {
        slug: "sector-62",
        name: "Sector 62",
        tagline: "IT hub · NH-24 · Fortis corridor",
        badge: "NOW LIVE — SECTOR 62",
        primaryFocus: "IT professionals & PG",
        heroDescription: "Sector 62 is Noida's busiest IT and PG belt — dense supply of flats, shared apartments and paying guest rooms near offices and metro.",
        coordinates: { lat: 28.627, lng: 77.3649 },
        popularAreas: ["Sector 62", "Sector 60", "Sector 63", "NH-24"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, 1–2 BHK flats and shared apartments." },
          { name: "Office Space", color: "#FF8F00", icon: "💼", desc: "Small offices and co-working pockets." },
        ],
        popularSearches: ["PG Sector 62 Noida", "Flat Sector 62", "1 BHK Sector 62 Noida"],
        faqs: [{ q: "Why is Sector 62 popular for rentals?", a: "Major IT parks, hospitals and metro access drive year-round demand for PG and working-professional flats." }],
        ctaHeading: "Sector 62 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-18",
        name: "Sector 18",
        tagline: "Atta Market · Metro · Commercial core",
        badge: "NOW LIVE — SECTOR 18",
        primaryFocus: "Metro-linked flats & PG",
        heroDescription: "Sector 18 combines Noida's top commercial market with strong metro connectivity — popular for PG, rooms and family flats.",
        coordinates: { lat: 28.5708, lng: 77.3261 },
        popularAreas: ["Sector 18", "Sector 16", "Sector 15", "Atta Market"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "PG, flats and builder floors near metro." },
        ],
        popularSearches: ["PG Sector 18 Noida", "Flat Sector 18", "Room rent Sector 18"],
        faqs: [],
        ctaHeading: "Sector 18 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-50",
        name: "Sector 50",
        tagline: "Central Noida · Metro · Family societies",
        badge: "NOW LIVE — SECTOR 50",
        primaryFocus: "Family flats & PG",
        heroDescription: "Sector 50 sits in central Noida with metro access and established societies — steady demand for 2–3 BHK flats and PG.",
        coordinates: { lat: 28.5745, lng: 77.356 },
        popularAreas: ["Sector 50", "Sector 51", "Sector 34", "Sector 41"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Society flats and builder floors." },
        ],
        popularSearches: ["Flat Sector 50 Noida", "2 BHK Sector 50", "PG Sector 50"],
        faqs: [],
        ctaHeading: "Sector 50 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-76",
        name: "Sector 76",
        tagline: "Aqua Line · Noida West gateway",
        badge: "NOW LIVE — SECTOR 76",
        primaryFocus: "Metro family rentals",
        heroDescription: "Sector 76 anchors the Noida West belt with Aqua Line metro — popular for family flats and professional PG near Sector 77–78 corridors.",
        coordinates: { lat: 28.6045, lng: 77.387 },
        popularAreas: ["Sector 76", "Sector 77", "Sector 78", "Sector 75"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Society flats and PG near metro." },
        ],
        popularSearches: ["Flat Sector 76 Noida", "PG Sector 76", "2 BHK Noida West"],
        faqs: [],
        ctaHeading: "Sector 76 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-137",
        name: "Sector 137",
        tagline: "Expressway · Metro · IT workforce",
        badge: "NOW LIVE — SECTOR 137",
        primaryFocus: "Expressway corridor flats",
        heroDescription: "Sector 137 along the Noida–Greater Noida Expressway sees strong IT and workforce rental demand — flats and PG near metro and offices.",
        coordinates: { lat: 28.5022, lng: 77.4118 },
        popularAreas: ["Sector 137", "Sector 135", "Sector 128", "Expressway"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and PG for expressway commuters." },
        ],
        popularSearches: ["Flat Sector 137 Noida", "PG Sector 137", "1 BHK expressway Noida"],
        faqs: [],
        ctaHeading: "Sector 137 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-15",
        name: "Sector 15",
        tagline: "Old Noida · Metro · Established blocks",
        badge: "NOW LIVE — SECTOR 15",
        primaryFocus: "Established residential",
        heroDescription: "Sector 15 is among older planned Noida sectors with mature housing stock — family flats, builder floors and PG near central markets.",
        coordinates: { lat: 28.585, lng: 77.3115 },
        popularAreas: ["Sector 15", "Sector 16", "Sector 17", "Sector 19"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Family flats and independent floors." },
        ],
        popularSearches: ["Flat Sector 15 Noida", "PG Sector 15", "2 BHK old Noida"],
        faqs: [],
        ctaHeading: "Sector 15 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-128",
        name: "Sector 128",
        tagline: "Jaypee Greens · Expressway · Premium",
        badge: "NOW LIVE — SECTOR 128",
        primaryFocus: "Premium societies & IT",
        heroDescription: "Sector 128 and Jaypee Wish Town belt — premium societies and expressway-linked flats popular with NCR professionals.",
        coordinates: { lat: 28.535, lng: 77.365 },
        popularAreas: ["Sector 128", "Sector 129", "Sector 127", "Wish Town"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Premium society flats and serviced units." },
        ],
        popularSearches: ["Flat Sector 128 Noida", "Jaypee Wish Town rent", "2 BHK Sector 128"],
        faqs: [],
        ctaHeading: "Sector 128 lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "greater-noida",
        name: "Greater Noida",
        tagline: "Knowledge Park · Pari Chowk · YEIDA",
        badge: "NOW LIVE — GREATER NOIDA",
        primaryFocus: "Value flats & student PG",
        heroDescription: "Greater Noida offers planned sectors, universities and industrial belts — affordable flats, PG and family homes across Knowledge Park and Pari Chowk corridors.",
        coordinates: { lat: 28.4744, lng: 77.504 },
        popularAreas: ["Knowledge Park", "Pari Chowk", "Alpha", "Beta", "Gamma"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Society flats and PG near colleges." },
        ],
        popularSearches: ["Flat Greater Noida", "PG Greater Noida", "Rent Knowledge Park"],
        faqs: [{ q: "Is Greater Noida cheaper than central Noida?", a: "Often yes for similar BHK — compare map pins across sectors before committing to advance." }],
        ctaHeading: "Greater Noida lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "noida-extension",
        name: "Noida Extension",
        tagline: "Greater Noida West · Gaur City · Metro",
        badge: "NOW LIVE — NOIDA EXTENSION",
        primaryFocus: "New societies & value flats",
        heroDescription: "Noida Extension (Greater Noida West) — high-volume new society flats and PG at competitive rents along Gaur City and Noida Metro corridors.",
        coordinates: { lat: 28.613, lng: 77.42 },
        popularAreas: ["Gaur City", "Sector 1 Extension", "Sector 4 Extension", "Tech Zone"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "New society 2–3 BHK and PG." },
        ],
        popularSearches: ["Flat Noida Extension", "PG Gaur City", "2 BHK Greater Noida West"],
        faqs: [],
        ctaHeading: "Noida Extension lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "sector-45",
        name: "Sector 45",
        tagline: "Central Noida · Hoshiarpur · DPS belt",
        badge: "NOW LIVE — SECTOR 45",
        primaryFocus: "Family housing",
        heroDescription: "Sector 45 and nearby central Noida pockets — established family rental demand with schools and markets within short drives.",
        coordinates: { lat: 28.554, lng: 77.352 },
        popularAreas: ["Sector 45", "Sector 46", "Sector 44", "Sector 34"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Family flats and builder floors." },
        ],
        popularSearches: ["Flat Sector 45 Noida", "2 BHK Sector 45", "Family flat central Noida"],
        faqs: [],
        ctaHeading: "Sector 45 lister?",
        ctaBody: "List on RentalPins.",
      },
    ],
  },
];
