// International city hubs (UK, Kenya, Nigeria) — merged into CITIES in cities-config.ts
import type { CityConfig } from "./rental-city-config-types";

export const INTERNATIONAL_CITIES: CityConfig[] = [
  {
    countrySlug: "uk",
    slug: "london",
    name: "London",
    country: "United Kingdom",
    tagline: "Central · East · South · West London — flats, rooms & short lets",
    badge: "NOW LIVE — LONDON",
    heroDescription:
      "Browse flats, rooms, houseshares and more to rent across Greater London on RentalPins — map-first discovery, contact listers directly. We are a marketplace, not a letting agent.",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    popularAreas: [
      "Camden", "Islington", "Hackney", "Tower Hamlets", "Southwark",
      "Lambeth", "Westminster", "Kensington & Chelsea", "Shoreditch", "Canary Wharf",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, houseshares, rooms and studios — check listings for bills, council tax and deposit details." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars, vans and bikes for short or longer-term hire where listed." },
      { name: "Electronics & Gadgets", color: "#FF8F00", icon: "💻", desc: "Laptops, cameras and kit for rent from local listers." },
    ],
    popularSearches: [
      "Flat to rent London", "Room to rent London", "2 bed flat rent Shoreditch",
      "Studio rent Camden", "Houseshare Hackney", "Short let Canary Wharf",
      "Rentals in Westminster", "Bills included flat London",
    ],
    faqs: [
      { q: "Is RentalPins a letting agency?", a: "No. RentalPins is a technology marketplace that connects listers and renters. We do not grant tenancies, hold deposits in escrow (unless a future product says otherwise), or substitute for your own checks on listings and listers." },
      { q: "What should I check before renting in England & Wales?", a: "Verify the landlord or agent, property condition, tenancy type, deposit protection (where a deposit is taken for an assured shorthold tenancy), safety certificates and local licensing (e.g. HMO). Seek independent legal advice for tenancy documents." },
      { q: "Are listings verified?", a: "We use account and technical signals to reduce abuse; we do not guarantee every listing. See our Terms and Privacy Policy for how we approach verification and reporting." },
    ],
    ctaHeading: "Have something to rent in London?",
    ctaBody: "List your room, flat or item and reach renters across London. Free to list on RentalPins — download the app to post in minutes.",
    status: "live",
    areas: [
      {
        slug: "greater-london",
        name: "Greater London",
        tagline: "All zones · central & inner London",
        badge: "LONDON — CITY WIDE",
        primaryFocus: "Flats & houseshares",
        heroDescription: "Search live pins across Greater London — from central zones to inner boroughs. Always confirm tenancy terms, right-to-rent checks and safety compliance with the lister.",
        coordinates: { lat: 51.5074, lng: -0.1278 },
        popularAreas: ["Zones 1–2", "Zones 3–4", "Inner East", "Inner South", "Inner West", "North London"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, rooms and studios across London boroughs." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and vans where listed." },
          { name: "Electronics", color: "#FF8F00", icon: "💻", desc: "Gadgets and equipment on rent." },
        ],
        popularSearches: ["Flat to rent London", "Room to rent London", "Studio London", "Short let London"],
        faqs: [
          { q: "How do I avoid rental scams?", a: "Never send money before viewing where possible, verify identities, use traceable payments, and report suspicious listings in the app. See our Terms for disclaimers." },
        ],
        ctaHeading: "Listing in London?",
        ctaBody: "Reach renters city-wide. Post from the RentalPins app.",
      },
      {
        slug: "camden",
        name: "Camden",
        tagline: "Camden Town · Kentish Town · Hampstead edges",
        badge: "LONDON — CAMDEN",
        primaryFocus: "Rooms & flats",
        heroDescription: "Popular with young professionals and students — browse rooms, flats and houseshares in and around the London Borough of Camden.",
        coordinates: { lat: 51.539, lng: -0.1426 },
        popularAreas: ["Camden Town", "Kentish Town", "Gospel Oak", "Swiss Cottage"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Rooms and flats near Camden markets and transport links." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Local mobility options on rent." },
          { name: "Furniture", color: "#5D4037", icon: "🛋️", desc: "Short-term furniture hires." },
        ],
        popularSearches: ["Room to rent Camden", "Flat Camden Town", "1 bed Kentish Town"],
        faqs: [{ q: "Transport?", a: "Northern line and Overground serve Camden; check commute times on listings." }],
        ctaHeading: "Renting out in Camden?",
        ctaBody: "List on RentalPins and appear on the map.",
      },
      {
        slug: "islington",
        name: "Islington",
        tagline: "Angel · Highbury · Finsbury Park edge",
        badge: "LONDON — ISLINGTON",
        primaryFocus: "Flats near Zone 2",
        heroDescription: "Dense rental demand near Angel and Upper Street — browse flats and rooms across Islington.",
        coordinates: { lat: 51.541, lng: -0.104 },
        popularAreas: ["Angel", "Highbury", "Canonbury", "Finsbury Park"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and houseshares." },
          { name: "Electronics", color: "#FF8F00", icon: "💻", desc: "Work-from-home kit on rent." },
        ],
        popularSearches: ["Flat rent Angel", "Room Islington", "2 bed near Highbury"],
        faqs: [],
        ctaHeading: "Lister in Islington?",
        ctaBody: "Post your spare room or flat on RentalPins.",
      },
      {
        slug: "hackney",
        name: "Hackney",
        tagline: "Dalston · London Fields · Homerton",
        badge: "LONDON — HACKNEY",
        primaryFocus: "Creative & young renter demand",
        heroDescription: "East London energy — rooms, flats and short lets around Hackney and Dalston.",
        coordinates: { lat: 51.545, lng: -0.055 },
        popularAreas: ["Dalston", "London Fields", "Homerton", "Stoke Newington"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Rooms and flats." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Bikes and cars." },
        ],
        popularSearches: ["Room rent Hackney", "Flat Dalston", "London Fields flat"],
        faqs: [],
        ctaHeading: "Hackney landlord?",
        ctaBody: "List free on RentalPins.",
      },
      {
        slug: "tower-hamlets",
        name: "Tower Hamlets",
        tagline: "Whitechapel · Bethnal Green · Isle of Dogs",
        badge: "LONDON — TOWER HAMLETS",
        primaryFocus: "City & Canary Wharf commute",
        heroDescription: "Strong demand near Elizabeth line and DLR — browse flats and rooms across Tower Hamlets.",
        coordinates: { lat: 51.509, lng: -0.006 },
        popularAreas: ["Whitechapel", "Bethnal Green", "Isle of Dogs", "Stepney"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and rooms." },
          { name: "Office", color: "#FF8F00", icon: "💼", desc: "Desk space where listed." },
        ],
        popularSearches: ["Flat Whitechapel", "Room Isle of Dogs", "Rent near Canary Wharf"],
        faqs: [],
        ctaHeading: "Listing in Tower Hamlets?",
        ctaBody: "Reach commuters on the map.",
      },
      {
        slug: "southwark",
        name: "Southwark",
        tagline: "London Bridge · Bermondsey · Peckham edges",
        badge: "LONDON — SOUTHWARK",
        primaryFocus: "Central south bank",
        heroDescription: "From London Bridge to Bermondsey — flats and rooms with strong transport links.",
        coordinates: { lat: 51.503, lng: -0.089 },
        popularAreas: ["London Bridge", "Bermondsey", "Elephant & Castle", "Canada Water"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats near Jubilee and Northern lines." },
        ],
        popularSearches: ["Flat Bermondsey", "Room London Bridge", "Rent Canada Water"],
        faqs: [],
        ctaHeading: "Southwark lister?",
        ctaBody: "Go live on RentalPins.",
      },
      {
        slug: "lambeth",
        name: "Lambeth",
        tagline: "Brixton · Clapham · Vauxhall",
        badge: "LONDON — LAMBETH",
        primaryFocus: "Young professional flats",
        heroDescription: "South of the river — Brixton, Clapham and Vauxhall rental hotspots on one map.",
        coordinates: { lat: 51.498, lng: -0.12 },
        popularAreas: ["Brixton", "Clapham", "Vauxhall", "Stockwell"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and houseshares." },
        ],
        popularSearches: ["Flat Brixton", "Room Clapham", "Studio Vauxhall"],
        faqs: [],
        ctaHeading: "Lambeth rentals?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "westminster",
        name: "Westminster",
        tagline: "West End · Victoria · Paddington edges",
        badge: "LONDON — WESTMINSTER",
        primaryFocus: "Premium central",
        heroDescription: "Central London demand — browse flats and short lets; verify pricing and licence terms with listers.",
        coordinates: { lat: 51.497, lng: -0.135 },
        popularAreas: ["West End", "Victoria", "Pimlico", "Marylebone"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Studios and flats." },
        ],
        popularSearches: ["Studio Westminster", "Flat Victoria", "Short let West End"],
        faqs: [],
        ctaHeading: "Central London lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "kensington-chelsea",
        name: "Kensington & Chelsea",
        tagline: "Kensington · Chelsea · Notting Hill edges",
        badge: "LONDON — RBKC",
        primaryFocus: "High-end flats",
        heroDescription: "Prime postcodes — always confirm deposits, references and agency status with the lister.",
        coordinates: { lat: 51.501, lng: -0.194 },
        popularAreas: ["Kensington", "Chelsea", "Earl's Court", "South Kensington"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and rooms." },
        ],
        popularSearches: ["Flat Chelsea", "Rent Kensington", "Studio South Ken"],
        faqs: [],
        ctaHeading: "RBKC landlord?",
        ctaBody: "List with RentalPins.",
      },
      {
        slug: "shoreditch",
        name: "Shoreditch",
        tagline: "Tech City · Spitalfields · Hoxton",
        badge: "LONDON — SHOREDITCH",
        primaryFocus: "Studios & creative lofts",
        heroDescription: "East London tech and nightlife hub — browse studios, flats and short lets.",
        coordinates: { lat: 51.5232, lng: -0.0872 },
        popularAreas: ["Shoreditch", "Spitalfields", "Hoxton", "Old Street"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Studios and flats." },
          { name: "Electronics", color: "#FF8F00", icon: "💻", desc: "AV and laptop hire." },
        ],
        popularSearches: ["Studio Shoreditch", "Flat Old Street", "Short let Spitalfields"],
        faqs: [],
        ctaHeading: "Shoreditch lister?",
        ctaBody: "Reach renters on RentalPins.",
      },
      {
        slug: "canary-wharf",
        name: "Canary Wharf & Isle of Dogs",
        tagline: "Canary Wharf · Poplar · Millwall",
        badge: "LONDON — DOCKLANDS",
        primaryFocus: "New-build flats",
        heroDescription: "Docklands and Canary Wharf — modern flats and rooms; confirm service charges and building rules with listers.",
        coordinates: { lat: 51.505, lng: -0.023 },
        popularAreas: ["Canary Wharf", "Poplar", "Millwall", "Blackwall"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats in towers and low-rises." },
        ],
        popularSearches: ["Flat Canary Wharf", "Rent Isle of Dogs", "Docklands studio"],
        faqs: [],
        ctaHeading: "Docklands landlord?",
        ctaBody: "List on RentalPins.",
      },
    ],
  },
  {
    countrySlug: "ke",
    slug: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    tagline: "Westlands · Kilimani · Karen — apartments, bedsitters & more",
    badge: "NOW LIVE — NAIROBI",
    heroDescription:
      "Find apartments, bedsitters, shared homes, vehicles and gear on rent across Nairobi on RentalPins. Contact listers directly; we are a marketplace — always inspect properties and agree terms in writing.",
    coordinates: { lat: -1.286389, lng: 36.817223 },
    popularAreas: [
      "Westlands", "Kilimani", "Karen", "Eastleigh", "South B", "Upper Hill",
      "Parklands", "Kasarani", "Mombasa Road", "Ngong Road",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Apartments, bedsitters, standalone houses and commercial space." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars, bikes and vans for personal or business use." },
      { name: "Electronics & Gadgets", color: "#FF8F00", icon: "💻", desc: "Laptops, generators and AV on rent." },
    ],
    popularSearches: [
      "House for rent Nairobi", "Apartment to let Westlands", "Bedsitter Kilimani",
      "Rent Karen Nairobi", "Short stay Nairobi", "Office Upper Hill",
    ],
    faqs: [
      { q: "Does RentalPins verify every landlord?", a: "We combine account verification and automated signals to reduce fraud, but we do not guarantee every listing. Meet in safe locations, inspect the property, and use traceable payments where possible." },
      { q: "What laws apply in Kenya?", a: "Kenya has data protection and consumer laws that may give you rights in addition to these Terms. Nothing here limits non-waivable rights under Kenyan law." },
    ],
    ctaHeading: "Have something to rent in Nairobi?",
    ctaBody: "List on RentalPins — download the app to post in minutes.",
    status: "live",
    areas: [
      {
        slug: "nairobi-metro",
        name: "Nairobi Metro",
        tagline: "CBD · Westlands · Eastlands",
        badge: "NAIROBI — CITY WIDE",
        primaryFocus: "All rental categories",
        heroDescription: "Browse listings across the Nairobi metropolitan area — map pins show approximate locations until you connect with the lister.",
        coordinates: { lat: -1.286389, lng: 36.817223 },
        popularAreas: ["CBD", "Westlands corridor", "Kilimani", "Thika Road", "Mombasa Road"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Apartments and bedsitters city-wide." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and bikes." },
        ],
        popularSearches: ["Rentals Nairobi", "Apartment Nairobi", "To let Nairobi"],
        faqs: [],
        ctaHeading: "Listing in Nairobi?",
        ctaBody: "Post from the RentalPins app.",
      },
      {
        slug: "westlands",
        name: "Westlands",
        tagline: "Rhapta Road · Waiyaki Way · Spring Valley",
        badge: "NAIROBI — WESTLANDS",
        primaryFocus: "Apartments & nightlife",
        heroDescription: "High-demand apartments and offices — browse Westlands on RentalPins.",
        coordinates: { lat: -1.267, lng: 36.81 },
        popularAreas: ["Rhapta Road", "Woodvale", "Spring Valley edge", "Waiyaki Way"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Apartments and bedsitters." }],
        popularSearches: ["Apartment Westlands", "Rent Rhapta Road", "Studio Westlands"],
        faqs: [],
        ctaHeading: "Westlands lister?",
        ctaBody: "Go live on RentalPins.",
      },
      {
        slug: "kilimani",
        name: "Kilimani",
        tagline: "Argwings Kodhek · Yaya · Hurlingham",
        badge: "NAIROBI — KILIMANI",
        primaryFocus: "Young professionals",
        heroDescription: "Popular Kilimani and Argwings Kodhek corridor — flats and shared homes.",
        coordinates: { lat: -1.292, lng: 36.787 },
        popularAreas: ["Kilimani", "Hurlingham", "Yaya", "Lavington edge"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and rooms." }],
        popularSearches: ["Flat Kilimani", "Apartment Argwings Kodhek", "Bedsitter Kilimani"],
        faqs: [],
        ctaHeading: "Kilimani rentals?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "karen",
        name: "Karen",
        tagline: "Karen Road · Hardy · Bogani",
        badge: "NAIROBI — KAREN",
        primaryFocus: "Family homes",
        heroDescription: "Leafy Karen — standalone houses and cottages on larger plots.",
        coordinates: { lat: -1.32, lng: 36.71 },
        popularAreas: ["Karen", "Hardy", "Langata South"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Houses and cottages." }],
        popularSearches: ["House rent Karen", "Cottage Karen", "Karen standalone"],
        faqs: [],
        ctaHeading: "Karen homeowner?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "eastleigh",
        name: "Eastleigh",
        tagline: "First Avenue · Business District",
        badge: "NAIROBI — EASTLEIGH",
        primaryFocus: "Commercial & dense residential",
        heroDescription: "Commercial and residential density — browse shops, rooms and flats.",
        coordinates: { lat: -1.283, lng: 36.85 },
        popularAreas: ["Eastleigh Section I", "Section III", "Airbase"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Rooms and commercial units." }],
        popularSearches: ["Shop rent Eastleigh", "Room Eastleigh", "Flat Eastleigh"],
        faqs: [],
        ctaHeading: "Eastleigh lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "south-b",
        name: "South B & South C",
        tagline: "Mombasa Road corridor",
        badge: "NAIROBI — SOUTH B/C",
        primaryFocus: "Affordable flats",
        heroDescription: "South B and South C — strong demand for flats and bedsitters near the expressway.",
        coordinates: { lat: -1.31, lng: 36.83 },
        popularAreas: ["South B", "South C", "Bellevue"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and bedsitters." }],
        popularSearches: ["Flat South B", "Rent South C", "Bedsitter South B"],
        faqs: [],
        ctaHeading: "South B/C landlord?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "upper-hill",
        name: "Upper Hill",
        tagline: "Hospital zone · offices",
        badge: "NAIROBI — UPPER HILL",
        primaryFocus: "Corporate & medical",
        heroDescription: "Nairobi's corporate ridge — offices and serviced apartments where listed.",
        coordinates: { lat: -1.3, lng: 36.81 },
        popularAreas: ["Upper Hill", "Hospital Rd", "Elgeyo"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Serviced apartments." },
          { name: "Office", color: "#FF8F00", icon: "💼", desc: "Office space." },
        ],
        popularSearches: ["Office Upper Hill", "Apartment Upper Hill"],
        faqs: [],
        ctaHeading: "Upper Hill lister?",
        ctaBody: "Reach businesses on RentalPins.",
      },
      {
        slug: "parklands",
        name: "Parklands",
        tagline: "Chiromo · 4th Ngong Avenue",
        badge: "NAIROBI — PARKLANDS",
        primaryFocus: "Mid-market apartments",
        heroDescription: "Parklands and Chiromo — apartments near Westlands and CBD.",
        coordinates: { lat: -1.26, lng: 36.82 },
        popularAreas: ["Parklands", "Chiromo", "Highridge"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Apartments." }],
        popularSearches: ["Flat Parklands", "Rent Chiromo"],
        faqs: [],
        ctaHeading: "Parklands lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "kasarani",
        name: "Kasarani & Roysambu",
        tagline: "Thika Road · USIU",
        badge: "NAIROBI — KASARANI",
        primaryFocus: "Students & families",
        heroDescription: "Thika Road corridor — high volume of bedsitters and flats.",
        coordinates: { lat: -1.22, lng: 36.9 },
        popularAreas: ["Kasarani", "Roysambu", "TRM Drive"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Bedsitters and flats." }],
        popularSearches: ["Bedsitter Kasarani", "Flat Roysambu", "Rent Thika Road"],
        faqs: [],
        ctaHeading: "Thika Road lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "mombasa-road",
        name: "Mombasa Road",
        tagline: "Industrial · logistics · airport corridor",
        badge: "NAIROBI — MOMBASA ROAD",
        primaryFocus: "Warehousing & staff housing",
        heroDescription: "Industrial and logistics belt — commercial units and staff housing where listed.",
        coordinates: { lat: -1.32, lng: 36.88 },
        popularAreas: ["Syokimau edge", "Mlolongo corridor", "Airport North"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Housing and yards." },
          { name: "Heavy equipment", color: "#5D4037", icon: "🏗️", desc: "Plant and machinery where listed." },
        ],
        popularSearches: ["Godown Mombasa Road", "House Syokimau", "Rent Mlolongo"],
        faqs: [],
        ctaHeading: "Mombasa Road lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "ngong-road",
        name: "Ngong Road",
        tagline: "Kilimani south · Ngong forest edge",
        badge: "NAIROBI — NGONG ROAD",
        primaryFocus: "New apartments",
        heroDescription: "Ngong Road corridor — new apartments and creative offices.",
        coordinates: { lat: -1.32, lng: 36.745 },
        popularAreas: ["Ngong Road", "Racecourse", "Karen link"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Apartments." }],
        popularSearches: ["Apartment Ngong Road", "Flat Kilimani south"],
        faqs: [],
        ctaHeading: "Ngong Road lister?",
        ctaBody: "List on RentalPins.",
      },
    ],
  },
  {
    countrySlug: "ng",
    slug: "lagos",
    name: "Lagos",
    country: "Nigeria",
    tagline: "Lekki · VI · Ikeja — flats, short lets & self contain",
    badge: "NOW LIVE — LAGOS",
    heroDescription:
      "Browse flats, self contain, mini flats, short lets and vehicles on rent across Lagos on RentalPins. We connect you with listers — inspect properties, verify identities and agree rent in writing before you pay.",
    coordinates: { lat: 6.5244, lng: 3.3792 },
    popularAreas: [
      "Lekki", "Victoria Island", "Ikoyi", "Ikeja", "Yaba", "Surulere",
      "Gbagada", "Ajah", "Maryland", "Festac",
    ],
    topCategories: [
      { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats, self contain, mini flats, short lets and commercial space." },
      { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars, buses and bikes." },
      { name: "Electronics & Gadgets", color: "#FF8F00", icon: "💻", desc: "Generators, AV and phones on rent." },
    ],
    popularSearches: [
      "Flat for rent Lekki", "Short let Lagos", "Self contain Yaba",
      "Mini flat Surulere", "Apartment VI", "Rent Ikeja GRA",
    ],
    faqs: [
      { q: "How do I stay safe when renting in Lagos?", a: "Inspect in person, verify ownership documents where possible, avoid cash-only pressure, and report suspicious listings. RentalPins uses verification signals but does not replace your own diligence." },
      { q: "Does Nigerian consumer law still apply?", a: "The Federal Competition and Consumer Protection Act and other laws may give you rights that cannot be waived. See our regional notices in the Terms and Privacy Policy." },
    ],
    ctaHeading: "Have something to rent in Lagos?",
    ctaBody: "List on RentalPins — download the app to post in minutes.",
    status: "live",
    areas: [
      {
        slug: "lagos-metro",
        name: "Lagos Metro",
        tagline: "Mainland · Island · Lekki corridor",
        badge: "LAGOS — CITY WIDE",
        primaryFocus: "All categories",
        heroDescription: "Greater Lagos — from Mainland hubs to the Lekki peninsula. Map pins are approximate until you message the lister.",
        coordinates: { lat: 6.5244, lng: 3.3792 },
        popularAreas: ["Island", "Mainland", "Lekki axis", "Ikeja GRA", "Surulere"],
        topCategories: [
          { name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and self contain." },
          { name: "Vehicles", color: "#1976D2", icon: "🚗", desc: "Cars and vans." },
        ],
        popularSearches: ["Rent Lagos", "Flat Lagos", "Short let Lagos"],
        faqs: [],
        ctaHeading: "Listing in Lagos?",
        ctaBody: "Post from the RentalPins app.",
      },
      {
        slug: "lekki",
        name: "Lekki",
        tagline: "Phase 1 · Ajah corridor · Ikate",
        badge: "LAGOS — LEKKI",
        primaryFocus: "New-build flats & short lets",
        heroDescription: "Lekki peninsula — apartments, duplexes and short-let flats; confirm service charges and estate rules.",
        coordinates: { lat: 6.4698, lng: 3.5851 },
        popularAreas: ["Lekki Phase 1", "Ikate", "Agungi", "Osapa"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and short lets." }],
        popularSearches: ["Flat Lekki Phase 1", "Short let Lekki", "Duplex Osapa"],
        faqs: [],
        ctaHeading: "Lekki lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "ikeja",
        name: "Ikeja",
        tagline: "GRA · Allen · Computer Village",
        badge: "LAGOS — IKEJA",
        primaryFocus: "Mainland premium",
        heroDescription: "Ikeja GRA and Allen — flats, mini flats and commercial frontages.",
        coordinates: { lat: 6.6018, lng: 3.3515 },
        popularAreas: ["Ikeja GRA", "Allen Avenue", "Adeniyi Jones", "Computer Village"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and shops." }],
        popularSearches: ["Flat Ikeja GRA", "Office Allen", "Mini flat Ikeja"],
        faqs: [],
        ctaHeading: "Ikeja landlord?",
        ctaBody: "Go live on RentalPins.",
      },
      {
        slug: "victoria-island",
        name: "Victoria Island",
        tagline: "Ahmadu Bello Way · Ozumba Mbadiwe",
        badge: "LAGOS — VI",
        primaryFocus: "Corporate & luxury short lets",
        heroDescription: "VI and Ozumba Mbadiwe — premium apartments and serviced flats.",
        coordinates: { lat: 6.4281, lng: 3.4219 },
        popularAreas: ["VI Core", "Ahmadu Bello", "Bonny Camp"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Luxury flats." }],
        popularSearches: ["Apartment VI", "Short let Victoria Island", "Serviced flat VI"],
        faqs: [],
        ctaHeading: "VI lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "yaba",
        name: "Yaba",
        tagline: "Tejuosho · Sabo · UNILAG edge",
        badge: "LAGOS — YABA",
        primaryFocus: "Students & tech",
        heroDescription: "Yaba and Sabo — self contain, mini flats and shared apartments near universities and startups.",
        coordinates: { lat: 6.5097, lng: 3.3717 },
        popularAreas: ["Sabo", "Tejuosho", "Herbert Macaulay"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Self contain and flats." }],
        popularSearches: ["Self contain Yaba", "Room Sabo", "Flat Tejuosho"],
        faqs: [],
        ctaHeading: "Yaba lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "surulere",
        name: "Surulere",
        tagline: "Adeniran Ogunsanya · Bode Thomas",
        badge: "LAGOS — SURULERE",
        primaryFocus: "Family flats",
        heroDescription: "Dense Surulere — flats and mini flats with strong mainland access.",
        coordinates: { lat: 6.5005, lng: 3.3581 },
        popularAreas: ["Adeniran", "Bode Thomas", "Ojuelegba edge"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and mini flats." }],
        popularSearches: ["Flat Surulere", "Mini flat Aguda", "Rent Bode Thomas"],
        faqs: [],
        ctaHeading: "Surulere lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "gbagada",
        name: "Gbagada",
        tagline: "Gbagada Expressway · Ifako",
        badge: "LAGOS — GBAGADA",
        primaryFocus: "Mid-market apartments",
        heroDescription: "Gbagada and Ifako — popular for commuters to Island and Ikeja.",
        coordinates: { lat: 6.5712, lng: 3.3915 },
        popularAreas: ["Gbagada", "Ifako", "Pedro"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats." }],
        popularSearches: ["Flat Gbagada", "Apartment Ifako"],
        faqs: [],
        ctaHeading: "Gbagada landlord?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "ajah",
        name: "Ajah & Sangotedo",
        tagline: "Lekki-Epe express",
        badge: "LAGOS — AJAH",
        primaryFocus: "New estates",
        heroDescription: "Ajah to Sangotedo — estate flats and family homes on the Lekki-Epe axis.",
        coordinates: { lat: 6.4683, lng: 3.6012 },
        popularAreas: ["Ajah", "Sangotedo", "Abraham Adesanya"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Estate flats." }],
        popularSearches: ["Flat Ajah", "Rent Sangotedo", "House Abraham Adesanya"],
        faqs: [],
        ctaHeading: "Ajah lister?",
        ctaBody: "Post on RentalPins.",
      },
      {
        slug: "ikoyi",
        name: "Ikoyi",
        tagline: "Dolphin · Osborne · Gerard",
        badge: "LAGOS — IKOYI",
        primaryFocus: "Premium apartments",
        heroDescription: "Ikoyi — high-end flats and short lets; verify service charges and building approvals.",
        coordinates: { lat: 6.4531, lng: 3.4224 },
        popularAreas: ["Osborne", "Dolphin", "Ikoyi SW"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Luxury flats." }],
        popularSearches: ["Flat Ikoyi", "Short let Osborne", "Apartment Gerard"],
        faqs: [],
        ctaHeading: "Ikoyi lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "maryland",
        name: "Maryland & Mende",
        tagline: "Ikorodu Road gateway",
        badge: "LAGOS — MARYLAND",
        primaryFocus: "Mainland flats",
        heroDescription: "Maryland and Mende — strong demand for flats near the Ikorodu express.",
        coordinates: { lat: 6.5767, lng: 3.3656 },
        popularAreas: ["Maryland", "Mende", "Palmgrove"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and mini flats." }],
        popularSearches: ["Flat Maryland Lagos", "Rent Mende"],
        faqs: [],
        ctaHeading: "Maryland lister?",
        ctaBody: "List on RentalPins.",
      },
      {
        slug: "festac",
        name: "Festac & Amuwo",
        tagline: "Festac Town · Mile 2",
        badge: "LAGOS — FESTAC",
        primaryFocus: "Family blocks",
        heroDescription: "Festac Town and Amuwo — block flats and family housing.",
        coordinates: { lat: 6.4709, lng: 3.2068 },
        popularAreas: ["Festac Phase 1", "Festac Phase 2", "Amuwo"],
        topCategories: [{ name: "Property", color: "#7B1FA2", icon: "🏠", desc: "Flats and duplexes." }],
        popularSearches: ["Flat Festac", "Rent Amuwo", "House Festac Town"],
        faqs: [],
        ctaHeading: "Festac lister?",
        ctaBody: "Post on RentalPins.",
      },
    ],
  },
];
