"use client";

import { useMemo, type RefObject } from "react";
import type { MapResultsPanelProps } from "@/components/map/MapResultsPanel";
import type { ListingFilters } from "@/lib/listing-filters";
import type { MapAreaShape } from "@/lib/map-area";
import type { MapListingDisplayItem } from "@/lib/map-building-groups";
import type { MapBounds } from "@/lib/types/saved-search";
import type { MapMobileView } from "@/components/map/MapMobileViewSwitcher";

type PanelProps = Omit<
  MapResultsPanelProps,
  "panelRef" | "sheetHandleRef" | "listRef" | "onSheetTrigger" | "onMobileViewChange"
>;

interface Options extends PanelProps {
  panelRef: RefObject<HTMLElement | null>;
  sheetHandleRef: RefObject<HTMLButtonElement | null>;
  listRef: RefObject<HTMLDivElement | null>;
  onMobileViewChange: (view: MapMobileView, method: "drag_handle") => void;
  onSheetTrigger: (el: HTMLButtonElement) => void;
}

/** Memoized prop bundle for MapResultsPanel. */
export function useMapResultsPanelProps(options: Options): MapResultsPanelProps {
  const {
    panelRef,
    sheetHandleRef,
    listRef,
    onMobileViewChange,
    onSheetTrigger,
    panelWidth,
    mobileView,
    onPanelResizeStart,
    filters,
    onFiltersChange,
    listings,
    filteredListings,
    totalInBounds,
    mapZoom,
    resultsMayBeIncomplete,
    loading,
    refreshing,
    fetchError,
    drawnShape,
    mapBounds,
    mapCenter,
    placeQuery,
    textQuery,
    selectedId,
    highlightedId,
    listDisplayItems,
    paginatedListItems,
    listPage,
    listTotalPages,
    onListPageChange,
    showListSkeletons,
    liveStatusText,
    countInfo,
    activeFilterCount,
    canResetView,
    onFitAll,
    onResetView,
    onClearFiltersOnly,
    onClearKeywordsFromEmpty,
    onClearDrawnAreaFromEmpty,
    onZoomInForMore,
    mapEmptyShow,
    mapEmptyVariant,
    mapEmptyTotalInBounds,
    mapEmptyFiltersActive,
    mapEmptyKeywordsActive,
    mapEmptyDrawnAreaActive,
    mapEmptyKeywordPreview,
    onHighlight,
  } = options;

  return useMemo(
    (): MapResultsPanelProps => ({
      panelRef,
      sheetHandleRef,
      listRef,
      panelWidth,
      mobileView,
      onMobileViewChange,
      onSheetTrigger,
      onPanelResizeStart,
      filters,
      onFiltersChange,
      listings,
      filteredListings,
      totalInBounds,
      mapZoom,
      resultsMayBeIncomplete,
      loading,
      refreshing,
      fetchError,
      drawnShape,
      mapBounds,
      mapCenter,
      placeQuery,
      textQuery,
      selectedId,
      highlightedId,
      listDisplayItems,
      paginatedListItems,
      listPage,
      listTotalPages,
      onListPageChange,
      showListSkeletons,
      liveStatusText,
      countInfo,
      activeFilterCount,
      canResetView,
      onFitAll,
      onResetView,
      onClearFiltersOnly,
      onClearKeywordsFromEmpty,
      onClearDrawnAreaFromEmpty,
      onZoomInForMore,
      mapEmptyShow,
      mapEmptyVariant,
      mapEmptyTotalInBounds,
      mapEmptyFiltersActive,
      mapEmptyKeywordsActive,
      mapEmptyDrawnAreaActive,
      mapEmptyKeywordPreview,
      onHighlight,
    }),
    [
      panelRef,
      sheetHandleRef,
      listRef,
      panelWidth,
      mobileView,
      onMobileViewChange,
      onSheetTrigger,
      onPanelResizeStart,
      filters,
      onFiltersChange,
      listings,
      filteredListings,
      totalInBounds,
      mapZoom,
      resultsMayBeIncomplete,
      loading,
      refreshing,
      fetchError,
      drawnShape,
      mapBounds,
      mapCenter,
      placeQuery,
      textQuery,
      selectedId,
      highlightedId,
      listDisplayItems,
      paginatedListItems,
      listPage,
      listTotalPages,
      onListPageChange,
      showListSkeletons,
      liveStatusText,
      countInfo,
      activeFilterCount,
      canResetView,
      onFitAll,
      onResetView,
      onClearFiltersOnly,
      onClearKeywordsFromEmpty,
      onClearDrawnAreaFromEmpty,
      onZoomInForMore,
      mapEmptyShow,
      mapEmptyVariant,
      mapEmptyTotalInBounds,
      mapEmptyFiltersActive,
      mapEmptyKeywordsActive,
      mapEmptyDrawnAreaActive,
      mapEmptyKeywordPreview,
      onHighlight,
    ]
  );
}
